### ISSUE TITLE
INSERT con WITH

### ISSUE THREAD

**Issue by fernanucm** [emartinm/lsql#100]
En el ejercicio PK 431 de la colección de acertijos he intentado incluir la siguiente instrucción para insertar las filas:

```
INSERT INTO t 
  WITH rec(s,a,n) AS (
    (SELECT 'abcdefghijkl',' ',0 FROM dual)
    UNION ALL
    (SELECT s,SUBSTR(s,n+1,1),n+1
    FROM rec
    WHERE n<LENGTH(s)))
  SELECT a FROM rec WHERE n>0;
```

En Oracle 11g es válida (lo he probado en mi instalación), pero Learn SQL devuelve:

ORA-00928: missing SELECT keyword

De momento lo he cambiado a inserciones con valores para evitar este problema.

**Comment by emartinm** [comment]
Como optimicé las inserciones para traducirlo todo a un único `INSERT ALL` más rápido, solo soporta inserciones del tipo `INSERT INTO .... VALUES (...)` porque el `INSERT ALL` solo soporta `VALUES`. Si ves que es una opción imprescindible podría cambiarlo para que si aparece algún `INSERT` que no es del tipo `INSERT INTO .... VALUES (...)` entonces se hagan las inserciones lentas una a una.

**Comment by fernanucm** [comment]
No es ningún inconveniente, mejor hacer los `INSERT` con `ALL`.
