### ISSUE TITLE
No muestra errores de PL/SQL al enviar una función incorrecta

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#16]
Al enviar algunas funciones PL/SQL para su corrección no se detectan correctamente los errores en su compilación. Por ejemplos esto pasa con:

    CREATE OR REPLACE FUNCTION golesLocal (pCadena VARCHAR2) RETURN NUMBER IS 
        ret NUMBER := TO_NUMBER(SUBSTRING(pCadena,1,1));
    BEGIN 
        RETURN ret;
    END;

Esto debería mostrar algún mensaje de que SUBSTRING no existe, ya que es algo que se detecta en la compilación. Sin embargo muestra un Internal Error como si hubiese fallado el servidor.

**Comment by iburgoa13** [comment]
Hola Enrique, perdón jeje, me he perdido
¿Hice pull? Estuve el otro día viendo algo de cómo hacerlo pero no subí
nada, no sé si es un comentario para tener yo en cuenta para mi nueva tarea
o qué.
Muchas gracias y disculpa las molestias!

**Comment by emartinm** [comment]
Resuelto en commit f52ad6b3b2805ff4ae2c47b2da11907425fc9d9c, tanto para funciones como procedimientos
