### ISSUE TITLE
Explicaciones en errores de validación del código

### ISSUE THREAD

**Issue by ningit** [emartinm/lsql#24]
Los errores de validación del código no indican las razones que hacen que no sea válido. Por ejemplo, introducir lo siguiente en el ejercicio *árbitros dirigiendo empates* produce un mensaje «*error de validación de tu código*» sin más detalles:
```sql
create view victorias_locales as select nif from enfrenta where goleslocal > golesvisitante;
select distinct nombre from victorias_locales inner join persona on victorias_locales.nif = persona.nif;
```
La solución es enrevesada y es razonable pensar que se espera una única sentencia o que no se pueden usar vistas, pero estaría bien que te lo dijese.

Si se deja únicamente el comando `create view` el mensaje de error es de tipo «*Error de conexión: Ha sido imposible conectar con el corrector de ejercicios. [...]*», que no parece que sea la explicación adecuada.

**Comment by emartinm** [comment]
¡Gracias por el comentario!

Los ejercicios de consultas SELECT esperan una única sentencia y de ahí sale el misterioso "error de validación". Habría que mejorar ese mensaje para que fuese realmente informativo.

El error de conexión al dejar únicamente el ```create view ...``` realmente es una situación inesperada al procesar la sentencia SQL que hace que falle el servidor y devuelva "500 Internal Server Error". Debería evitarse que falle el servidor y sobre todo mostrar un mensaje más informativo.

**Comment by emartinm** [comment]
El contenido de los mensajes asociados a errores de validación ha sido ligeramente mejorado en el commit e774c2e. Ahora indica si es porque el número de sentencias SQL es incorrecto.

**Comment by emartinm** [comment]
También se ha mejorado el manejo de sentencias SQL que no devuelven nada (como `CREATE VIEW` o `INSERT`) en ejercicios de SELECT. Ahora se indica que el esquema vacío del resultado (sin columnas) es diferente del esperado. 

Incluido en el commit a6aa649.

@ningit , si consideras que estos cambios resuelven tu comentario avísame y cierro este issue.

**Comment by ningit** [comment]
¡Gracias! Los mensajes ahora son muy claros. Me parece que está resuelto.

**Comment by emartinm** [comment]
La verdad es que podía haber incluido capturas de pantalla para ilustrarlo mejor, pero veo que has podido probarlo en el servidor sin problema. Cierro el _issue_.
