### ISSUE TITLE
Tarea fechas Resultados

### ISSUE THREAD

**Issue by iburgoa13** [emartinm/lsql#34]
Hola Enrique, como hemos hablado y me parece buena idea, hablo por aquí y si los demás compañeros tienen dudas como la que puedo tener yo, se puede resolver. He terminado la tarea (faltarían test) pero quería comprobar pylint y me sale esto y no sé de qué puede ser:
![imagen](https://user-images.githubusercontent.com/43571438/109826164-d1847b80-7c3a-11eb-86c1-e58fd70635c5.png)
Y estos los códigos:
![imagen](https://user-images.githubusercontent.com/43571438/109826224-de08d400-7c3a-11eb-96a5-bb4efa48f037.png)
![imagen](https://user-images.githubusercontent.com/43571438/109826255-e5c87880-7c3a-11eb-8212-454dcd19d139.png)
El otro día me suena pasar pylint con el firstDayOfCourse y ahora no... no sé por qué

**Comment by iburgoa13** [comment]
¿Puede deberse a que tienen returns que no son comprobados en test?

**Comment by emartinm** [comment]
Yo creo que únicamente se queja de que las funciones tienen que usar snake_case, es decir debe ser `first_day_of_course()`. Hace poco he actualizado requirements.txt y creo que hay una versión más nueva de pylint, quizá por eso antes no se quejaba (quién sabe?)

**Comment by iburgoa13** [comment]
Vale, eso era, como ya tenía el requirements.txt siempre actualizado me dio pereza hacer ese paso siempre, ahora al yo bajarme tus cambios no lo he actualizado y fallaba, da ya 10
![imagen](https://user-images.githubusercontent.com/43571438/109830040-650b7b80-7c3e-11eb-9724-66abfa1b7a16.png)
Y por si acaso cambié los nombres como bien dijiste:
![imagen](https://user-images.githubusercontent.com/43571438/109830135-7a80a580-7c3e-11eb-88af-5ebc11ab49b1.png)
![imagen](https://user-images.githubusercontent.com/43571438/109830163-82404a00-7c3e-11eb-9565-0120610935d4.png)
Gracias!

**Comment by emartinm** [comment]
snake_case es mas Python, dejemos CamelCase para Java y amigos :-)

**Comment by emartinm** [comment]
@iburgoa13 acabo de subir un commit 3fafb2cd80dd3b0bffed73d1845780b99c7bc7f2 adaptando los tests de unidad para dejar de usar tanto `assertTrue`, que me daba un poco de vergüenza.

También he hecho un par de cambios en views.py renombrando alguna función como `for_loop` por nombres que entendiera mejor, ampliando los comentarios y usando un `for` con `enumerate` porque pylint se quejaba. Realmente son 5 cosas, espero que no te dé conflicto cuando actualices (si no has tocado exactamente esas líneas debería poder mezclar de manera automática).

**Comment by iburgoa13** [comment]
Hola Enrique, entiendo lo de los assertTrue.. intentaré en próximos no ponerlos y usar equals o in...
He visto los cambios, me daban conflictos, sí por que ahora con las fechas justo esos dos métodos los pasaba por parámetro, creo haberlos arreglado ya.

**Comment by emartinm** [comment]
No, si lo que me daba vergüenza era que los tests que había escrito yo eran mayoría y encima eran lo peores. Por eso me puse a precisar los `assertTrue` y creo que el 95% eran míos (sí, al principio únicamente usaba `assertTrue`...).

> He visto los cambios, me daban conflictos, sí por que ahora con las fechas justo esos dos métodos los pasaba por parámetro, creo haberlos arreglado ya.

Vaya, pues lo siento mucho, no era mi intención generarte conflictos :-( Tengo pensado añadir una nueva ruta y tocar el fichero settings.py, pero eso sí que no tendrá ninguna colisión con nada de lo que puedas estar haciendo.

**Comment by iburgoa13** [comment]
En settings.py tuve que añadir dos líneas, mira si quieres mi settings.py de mi rama.
Básicamente son dos líneas por tema de fechas, que en comprobaciones del create_date de Submission me daba un warning y encontré en Internet que pusiera eso, si molesta dimelo

**Comment by emartinm** [comment]
¿En cuál de los 4 ficheros de settings? ¿Me puedes pasar un enlace a la línea concreta para que sepa cuáles son los cambios?

Si me indicas la URL para que entienda el warning que daba y como se arreglaba también te lo agradezco.

**Comment by emartinm** [comment]
Pero esas dos cosas están activadas en https://github.com/iburgoa13/lsql/blob/fechas_resultados/lsql/lsql/settings_shared.py#L125 porque se generan así en los settings por defecto. Si hubiera que cambiarlo se haría en `setting_shared` y no ponerlas a True y luego sobreescribir a False.

De todas formas explícame con un poco más de detalle cuál era el aviso que recibías, de quién era el aviso (pylint? Django?) y por qué desactivar las zonas horarias y el manejo local de fechas es la mejor forma de resolverlo.

**Comment by iburgoa13** [comment]
Vale, cierto es, no lo ví.
No es un fallo, solamente un warning por las fechas y no era ni pylint ni django cuando ponía un print me saltaba ese warning como de la hora.

**Comment by iburgoa13** [comment]
Lo he quitado y pylint pasa.
Lo que me sale en pantalla es esto
![imagen](https://user-images.githubusercontent.com/43571438/109952006-a8b5c200-7cde-11eb-8e4a-b725fdf537a2.png)
Pero lo pasa.. por eso lo puse.

**Comment by emartinm** [comment]
¿Sospecho que esto te pasa al hacer tests de unidad y poner a mano una fecha para un submission (que todavía no estamos 100% seguros de que sirva, revisa que no lo sobreescriba)?

Si esa fecha la estás creando tú a mano, añade un timezone también, que creo que por eso se queja.

**Comment by iburgoa13** [comment]
Todavía no he empezado con ningún test... es todo de código

**Comment by iburgoa13** [comment]
Será de esto? 
![imagen](https://user-images.githubusercontent.com/43571438/109955413-bf5e1800-7ce2-11eb-8999-0a25aed9e638.png)
Recojo el parámetro de GET y hago eso que es lo que encontré que es como se comprueba...

**Comment by iburgoa13** [comment]
No sé de qué será , pero todo funciona bien y pylint da 10.. He quitado eso de settings. Cuando haga los test miraré.

**Comment by emartinm** [comment]
Sí, si `start` y `end` los creas tú a partir de cadenas de texto es posible que no se incorpore ningún timezone y que al filtrar lance ese aviso. Prueba a comentar esa línea a ver si desaparece. Porque en todo el código que tienes hasta ahora no creas una submission a mano en ningún sitio, ¿verdad?

Si ese mensaje antes no aparecía y ahora sí entonces es muy posible que esté causado por el código nuevo, así que vamos a apuntarlo para solucionarlo cuando llegue el momento.

**Comment by iburgoa13** [comment]
Tiene que ser por eso 100% porque en ningún otro lado lo llamo ni nada, solo en 2 sitios para las subs y ya... pensaba que eso es un filtro de dame todas en las que estén entre este ranfo de fechas..

**Comment by emartinm** [comment]
Si haces la consulta sin filtrar por fechas y desaparece el mensaje entonces seguro que es ahí.

Para filtrar no debería crear objetos `Submission` nuevos, pero realmente no sabemos nada sobre cómo está implementado el ORM de Django (al menos yo). Así que cualquier cosa es posible

**Comment by iburgoa13** [comment]
Yo me guié en esto
https://stackoverflow.com/questions/4668619/how-do-i-filter-query-objects-by-date-range-in-django
Pero poniendo a False aquello no daba fallos, pero bueno, ya se verá.

**Comment by iburgoa13** [comment]
Estoy acabando ya todo, me está dando problemas el pylint.
![imagen](https://user-images.githubusercontent.com/43571438/110204163-f6166880-7e71-11eb-83dc-e1e137996c5c.png)
Si quito lo de la excepcion me sale que no le puedo meter mas return porque tiene un limit, lo otro ya miraré, no hay forma que pylint sea menos exigente? Llevo un buen rato intentando corregir ese pequeño detalle y por un return no me dejará hacer PR.
