### ISSUE TITLE
Tarea descargar ranking (dificultad baja)

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#35]
Tarea para @Tamiflu9 

Descargar el listado de envíos de la pestaña 'Resultados' como fichero Excel o CSV si no se puede.

Como todavía Iker está terminando el manejo de fechas en el el ranking #34, empieza investigando cómo crear ficheros Excel y cómo se genera el ranking de resultados.

**Comment by Tamiflu9** [comment]
He estado buscando y en la documentación de django si que he encontrado como generar CSV utilizando la biblioteca csv de python. Podría hacerlo en formato csv?

Y por otro lado, entiendo que solo los profesores son los que se pueden descargar el ranking no?

**Comment by emartinm** [comment]
Generar CSV o Excel es una tarea completamente independiente de Django, así que no te limites a buscar únicamente información relacionada con Django para esa tarea. 

CSV valdría, pero creo que quedaría más bonito generar una hoja de cálculo. Por ejemplo con esta biblioteca se pueden crear fácilmente hojas de cálculo ODS: https://github.com/pyexcel/pyexcel-ods. Concretamente se salvan los datos como se en https://github.com/pyexcel/pyexcel-ods#write-to-an-ods-file. Echa un vistazo a ver si te convence, porque es tan fácil (o más) que generar un CSV.

**Comment by emartinm** [comment]
Si al final se utiliza alguna biblioteca de PyPi, habrá que actualizar `requirements.txt` adecuadamente

**Comment by Tamiflu9** [comment]
Si, si no también encontré otra biblioteca: `openpyxl`, pero miraré la que me has dicho.

**Comment by Tamiflu9** [comment]
Es mejor hacer una función el `views.py` y ahí hacer la escritura en el archivo, o puedo hacerlo directamente en `results.html`?

**Comment by Tamiflu9** [comment]
De momento he conseguido esto:

![2](https://user-images.githubusercontent.com/33600064/110249048-4d9cfd00-7f74-11eb-86ca-0f7884967371.png)

No se muy bien como cambiar de fila, ni porque salen todos los paréntesis. 

Tampoco se porque no me imprime todos los nombres de los problemas si por consola si lo hace 

![3](https://user-images.githubusercontent.com/33600064/110249100-b2585780-7f74-11eb-9499-739b772d5ada.png)

Lo que tengo de código es esto: (los paréntesis vacíos sobran)

![1](https://user-images.githubusercontent.com/33600064/110249108-c308cd80-7f74-11eb-99e0-e6f2dfd2ea22.png)

**Comment by emartinm** [comment]
> Es mejor hacer una función el `views.py` y ahí hacer la escritura en el archivo, o puedo hacerlo directamente en `results.html`?

Esta pregunta no la entiendo. `results.html` es una plantilla, así que ahí no puedes definir ninguna función. Si la pregunta es si meter el código que genera el ODS dentro de `download_ranking` o hacer una función separada e invocarla, mi contestación sería "depende de la complejidad". Si necesitas más de 10-15 líneas para generar el fichero yo lo separaría en una función diferente porque es una tarea muy diferenciada de la generación de la página.

> No se muy bien como cambiar de fila, ni porque salen todos los paréntesis.
Tampoco se porque no me imprime todos los nombres de los problemas si por consola si lo hace

Nunca he usado esa biblioteca así que no te puedo ayudar en eso. ¿Has consultado la documentación en http://docs.pyexcel.org/en/latest/index.html? Es mucho más detallada que los pequeños ejemplos que aparecen en su GitHub.

**Comment by Tamiflu9** [comment]
Para lo del archivo que se genera en la carpeta de test, he probado a borrarlo con `remove('book.ods')` y funciona.

**Comment by emartinm** [comment]
1. Como se trata de un servidor web pueden llegar varias peticiones simultáneas para descargar rankings diferentes, por lo que usar el mismo nombre de fichero es un problema. Usa https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp para generar ficheros con nombres diferentes y luego bórralos con `os.remove`.

2. Existe un decorador para limitar ciertas vistas al staff (similar al `login_required`). Lo digo porque es más limpio que hacer un IF dentro.

3. Lo ideal es que reutilices el código de Iker para generar el ranking, porque no tiene sentido hacerlo dos veces. Y con ese resultado te limites a introducirlo en el fichero Excel.

4. Creo que no estoy entendiendo bien a qué tipo de funciones te refieres a la hora de pasarle varios parámetros. ¿Es la función de una vista? En este caso te llegarán como argumentos HTTP en el diccionario `request.GET`. Pero lo de las fechas todavía no está incorporado, aunque está muy cerca.

**Comment by emartinm** [comment]
Para la tarea 3 he comprobado que puedes invocar a la función `show_result(request, collection)` y extraer el código HTML de la respuesta. Para que te sea sencillo encontrar la tabla con el ranking dentro del HTML creo que lo mejor es asignar un identificador a esa tabla, en la línea https://github.com/emartinm/lsql/blob/f9dcfdee08692e174e3eb2d830635b5e02e77c29/lsql/judge/templates/results.html#L86 y buscar por ese identificador.

Una vez tienes la tabla HTML con el ranking puedes pasarlo al fichero Excel. Para encontrar la tabla y recorrerla te puede resultar útil bs4: https://www.crummy.com/software/BeautifulSoup/bs4/doc/

**Comment by Tamiflu9** [comment]
![1](https://user-images.githubusercontent.com/33600064/111068582-a7984800-84c9-11eb-9857-0033c124dacc.png)

Me imagino que el html que necesito está en `text/html` , para quedarme solo con eso no se muy bien como hacerlo.

**Comment by Tamiflu9** [comment]
Con `html_doc = show_result(request,collection_id)['Content-Type']` obtengo : '`text/html; charset=utf-8`' . No se si es un avance o estoy tirando por mal camino.

**Comment by Tamiflu9** [comment]
Con ` html = show_result(request,collection_id).content.decode('utf-8) ` ya he conseguido:  

`<ul class="errorlist"><li>group<ul class="errorlist"><li>This field is required.</li></ul></li><li>start<ul class="errorlist"><li>This field is required.</li></ul></li><li>end<ul class="errorlist"><li>This field is required.</li></ul></li></ul>`

Lo que no entiendo es porque me da error si las fechas y el grupo son correctos.

**Comment by emartinm** [comment]
> Con `html_doc = show_result(request,collection_id)['Content-Type']` obtengo : '`text/html; charset=utf-8`' . No se si es un avance o estoy tirando por mal camino.

`show_result` devuelve una contestación HTTP igual que las que recibes y compruebas en los test de unidad. Usa el mismo código para extraer el contenido de la página HTML de ahí (veo que ya lo has hecho).

> Lo que no entiendo es porque me da error si las fechas y el grupo son correctos.

El objeto `request` que pases a `show_result` tiene que tener los parámetros GET que se indican: group, start y end. El mensaje que recibes es porque el objeto `request` que estás pasando no tiene ninguno de los 3. Si la ruta que estás haciendo se llama (me lo invento) /download_result/<collection>/, tienes que asegurarte de que la llamas con esos parámetros: /download_result/<collection>?group=3&start=2021-02-21&end=2021-03-15. De esta manera podrás reutilizar tu request para invocar a `show_result` y tendrá todos los parámetros (además de poder reutilizar la validación de parámetros que hace `show_result`)

**Comment by Tamiflu9** [comment]
Tuve algunos problemas para que me reconociera los fechas en el formato de año-mes-día pero está solucionado. Lo que no he conseguido es que me detecte el `group.id` y no se muy bien porque no lo reconoce.

He hecho pruebas metiéndole el número del grupo directamente para ir organizando el meter los datos en el excel y he añadido más identificadores porque no he sabido como hacerlo de otra manera para poder ir viendo cuantas columnas dejar por cada ejercicio de una colección o cuando cambiar de fila cada vez que cambiaba de alumno. Tiene esta pinta:

![ranking](https://user-images.githubusercontent.com/33600064/111316027-3391a780-8663-11eb-88e7-bdc1238f1440.png)

**Comment by Tamiflu9** [comment]
Se me había olvidado meter el grupo. Quedaría así: 

![ranking](https://user-images.githubusercontent.com/33600064/111319462-51144080-8666-11eb-850c-5471ebfd73f7.png)

![ranking](https://user-images.githubusercontent.com/33600064/111319145-fb3f9880-8665-11eb-970e-44e2e64d8b1a.png)

**Comment by emartinm** [comment]
> Lo que no he conseguido es que me detecte el `group.id` y no se muy bien porque no lo reconoce.

No sé exactamente a qué te refieres con "detectar el `group.id`"



> he añadido más identificadores porque no he sabido como hacerlo de otra manera para poder ir viendo cuantas columnas dejar por cada ejercicio de una colección o cuando cambiar de fila cada vez que cambiaba de alumno

Entiendo que todas las filas tendrán el mismo número de columnas, que será el número de celdas que tenga la cabecera. No sé si estarás recorriendo la tabla como secuencia de celdas `<td>`, pero si es así será mejor que primero detectes el `<thead>` y su única `<tr>` formada por celdas `<th>`. Luego dentro del `<tbody>` detecta fila por fila (`<tr>`) y luego ya dentro las celdas `<td>` que será el mismo número por fila. Pero entiendo que te dará igual saber el número de antemano si estás recorriendo las entradas de una única fila.

**Comment by Tamiflu9** [comment]
> No sé exactamente a qué te refieres con "detectar el `group.id`"

`<div class="col md-3">
            <a href="{% url 'judge:download_ranking' collection.id %}?group={{`**`group.id`**}`}&start={{start_date|date:'Y-m-d'}}&end={{end_date|date:'Y-m-d'}}">
            <button type="button" class="btn btn-primary" title="csv con el ranking">Ranking</button>
            </a>
        </div>`

Cuando le paso el `grupo.id` ahí lo coge como si no hubiera grupo, pero si le pongo un 2 ya si que lo detecta como el 'Grupo B'

 
> Entiendo que todas las filas tendrán el mismo número de columnas, que será el número de celdas que tenga la cabecera. No sé si estarás recorriendo la tabla como secuencia de celdas `<td>`, pero si es así será mejor que primero detecta el `<thead>`y su única `<tr>`formada por celdas `<th>`. Luego dentro del `<tbody>`detecta fila por fila ( `<tr>`) y luego ya dentro las celdas `<td>`que será el mismo número por fila. Pero entiendo que te dará igual saber el número de antemano si estás recorriendo las entradas de una única fila.

Ah vale si, que me había centrado en coger solo las etiquetas `<td>` o `<th>` y no las anteriores `<thead>` y `<tbody>`. Voy a probar asi.

**Comment by emartinm** [comment]
Como no sé de dónde viene ese `group` que se le pasa a la plantilla no sé si es un objeto tipo `Group`, una cadena de texto u otra cosa. Haz pruebas con ese valor **antes** de pasarlo a la plantilla, por ejemplo mira el contenido y el tipo mediante `print`, para ver exactamente qué contiene.

**Comment by Tamiflu9** [comment]
He intentado imprimir el valor de `group.id` y esta vacío..
Lo cojo directamente del `<form...>...</form>` de results.html o eso pensé que hacía
https://github.com/emartinm/lsql/blob/7cf13fc9bc20f446ba4d858350a30517ba1ec5a7/lsql/judge/templates/results.html#L21

Como con las fechas, que solo he puesto estos valores:
https://github.com/emartinm/lsql/blob/7cf13fc9bc20f446ba4d858350a30517ba1ec5a7/lsql/judge/templates/results.html#L27
https://github.com/emartinm/lsql/blob/7cf13fc9bc20f446ba4d858350a30517ba1ec5a7/lsql/judge/templates/results.html#L30

**Comment by emartinm** [comment]
Si en esa misma plantilla se usa `group.id` y sí existe, no entiendo por qué cuando lo vas a usar tú no está definido :-o ¿Qué tipo tiene el valor que se pasa en el parámetro de plantilla `group` **justo antes de renderizar la plantilla**? Usa la función `type()` para saberlo.

**Comment by Tamiflu9** [comment]
Me sale: `<class 'django.contrib.auth.models.Group'>` y he visto que se llama `group0.id` en vez de `group.id` y acabo de probar con `group0.id` y funciona (cosa que ayer no funcionó, pero no se si es que de tantos cambios se quedó por ahí algo pillado o no se).

**Comment by Tamiflu9** [comment]
Para actualizar el requirements.txt basta con poner las filas nuevas que me salen al hacer `pip list`?
Las bibliotecas nuevas que uso son:
```
from bs4 import BeautifulSoup
import xlsxwriter
from os import remove
import tempfile
```
Como a mi ya me aparecían más cosas haciendo `pip list` desde el principio no se muy bien si he metido todo lo necesario, creo que con esto bastaría:

```
beautifulsoup4==4.9.3
soupsieve==2.2
XlsxWriter==1.3.7
```
Para usar tempfile creo que no instalé nada.

Y luego, que test tengo que hacer?

**Comment by emartinm** [comment]
Lo más sencillo para actualizar el fichero `requirements.txt` es ejecutar `pip freeze` y copiar directamente todo lo que te aparezca, que serán todos los paquetes que has instalado y sus versiones actuales. Antes de hacer esto asegúrate que has quitado todos los paquetes que puedas haber instalado para pruebas y al final no usas (con `pip uninstall`).

**Comment by emartinm** [comment]
> Y luego, que test tengo que hacer?

Te devuelvo la pregunta: ¿qué crees que deberías comprobar para saber que tu mejora funciona como se espera?

**Comment by Tamiflu9** [comment]
Igual me estoy haciendo un lio a la hora de hacer el test que compruebe el contenido del fichero que se descarga el ranking. En `test_view.py` no tengo que generar ningún archivo ni nada, solo crear usuario, grupo, problemas, envíos, etc. hacer el envío con el usuario que sea y ya tendría datos en la tabla del ranking y luego abrir el archivo que se tendría que haber descargado y comprobar alguna celda, no?

Con la biblioteca que uso no puedo abrir archivos, solo crearlos y escribir en ellos. He probado a usar otra ( `openpyxl` ) para hacer tanto la escritura como intentar leer el fichero una vez creado y si que me funciona solo que el formato `.ods` no es posible usarlo, solo admite: `.xlsx,.xlsm,.xltx,.xltm`.

**Comment by emartinm** [comment]
> Igual me estoy haciendo un lio a la hora de hacer el test que compruebe el contenido del fichero que se descarga el ranking. En `test_view.py` no tengo que generar ningún archivo ni nada, solo crear usuario, grupo, problemas, envíos, etc. hacer el envío con el usuario que sea y ya tendría datos en la tabla del ranking y luego abrir el archivo que se tendría que haber descargado y comprobar alguna celda, no?

No entiendo bien qué quieres decir con "generar un archivo". Lo que tienes que comprobar es que al invocar a tu nueva vista en un escenario de usuarios, problemas, colecciones, grupos y envíos concreto se descarga un fichero Excel con el contenido esperado en algunas celdas (si son pocas puedes comprobarlas todas). Para generar ese escenario te puedes basar en el test que ya hizo Iker (si vas a reutilizarlo exactamente igual sácalo a una función externa y que lo usen ambos tests). También sería importante que compruebes que los accesos están correctamente limitados, es decir que únicamente los profesores pueden descargarlo. Usas el mismo formulario que Iker para validar las entradas del usuario, ¿no? Si es así no será necesario que compruebes la validación de start, end y group.

> Con la biblioteca que uso no puedo abrir archivos, solo crearlos y escribir en ellos. He probado a usar otra ( `openpyxl` ) para hacer tanto la escritura como intentar leer el fichero una vez creado y si que me funciona solo que el formato `.ods` no es posible usarlo, solo admite: `.xlsx,.xlsm,.xltx,.xltm`.

Creo que usar dos bibliotecas para leer y escribir es un poco raro, casi mejor utilizar una sola aunque lo que se baje se un Excel (que viene a ser lo mismo).

**Comment by Tamiflu9** [comment]
> No entiendo bien qué quieres decir con "generar un archivo". Lo que tienes que comprobar es que al invocar a tu nueva vista en un escenario de usuarios, problemas, colecciones, grupos y envíos concreto se descarga un fichero Excel con el contenido esperado en algunas celdas (si son pocas puedes comprobarlas todas). 

Vale, es que por un momento pensé en crear un nuevo archivo y guardar los datos y luego comprobarlos, peor eso no es. Tendría que comprobar en `response.content.decode('UTF-8')` el contenido? o no se muy bien de donde sacar el contenido de ese excel. Acabo de ver que el contenido de `response.content` es algo asi:
![content](https://user-images.githubusercontent.com/33600064/111881757-52b96d80-89b2-11eb-886e-c23ae98d50c1.png)

> Para generar ese escenario te puedes basar en el test que ya hizo Iker (si vas a reutilizarlo exactamente igual sácalo a una función externa y que lo usen ambos tests). 

Lo he reducido mucho, a un solo usuario con un ejercicio y un grupo. Que no haría falta introducir tantos datos para este test no?

>También sería importante que compruebes que los accesos están correctamente limitados, es decir que únicamente los profesores pueden descargarlo. 

Para eso he hecho:

`url = reverse('judge:download_ranking', args=[collection.pk])
        response = client.get(url, {'group': group_a.id, 'start': start, 'end': end}, follow=True)

        # Teacher download ranking
        self.assertEqual(
            response.get('Content-Disposition'),
            "attachment; filename=ranking.xlsx",
        )
        self.assertEqual(
            response.get('Content-Type'),
            "application/xlsx"
        )

        # User can't download ranking
        client.logout()
        client.login(username=user.username, password='2222')
        response = client.get(url, {'group': group_a.id, 'start': start, 'end': end}, follow=True)
        self.assertIn('Forbidden', response.content.decode('UTF-8'))`

> Usas el mismo formulario que Iker para validar las entradas del usuario, ¿no? Si es así no será necesario que compruebes la validación de start, end y group.

Yo en mi función en un principio no validaba nada porque como cogía los datos directamente de Iker y él ya hace la validación antes de usarlos yo

**Comment by emartinm** [comment]
> Vale, es que por un momento pensé en crear un nuevo archivo y guardar los datos y luego comprobarlos, peor eso no es. Tendría que comprobar en `response.content.decode('UTF-8')` el contenido? o no se muy bien de donde sacar el contenido de ese excel. Acabo de ver que el contenido de `response.content` es algo asi:

`response.content` como bien se ve en tu prueba es un binario con el contenido del Excel. Tendrías que ser capaz de crear un objeto "fichero excel" de tu biblioteca a partir de ese binario (idealmente sin volcarlo en un fichero local en el disco duro para no dejar basura). 

> Lo he reducido mucho, a un solo usuario con un ejercicio y un grupo. Que no haría falta introducir tantos datos para este test no?

Si lo tienes ya funcionando déjalo así.

> Para eso he hecho:

Sí, ese código parece comprobar que los alumnos no pueden acceder.

> Yo en mi función en un principio no validaba nada porque como cogía los datos directamente de Iker y él ya hace la validación antes de usarlos yo

Si pasas tu `request` a la función de Iker es verdad que se realizarán las mismas validaciones, pero entonces tienes que detectar cuando la función de Iker devuelve errores de validación para devolverlos tú también. Para comprobar que esto lo estás haciendo bien, añade en tu test de unidad una petición que tenga fechas o grupo incorrecto para verificar que está todo bien conectado.

**Comment by Tamiflu9** [comment]
> `response.content` como bien se ve en tu prueba es un binario con el contenido del Excel. Tendrías que ser capaz de crear un objeto "fichero excel" de tu biblioteca a partir de ese binario (idealmente sin volcarlo en un fichero local en el disco duro para no dejar basura).

No he encontrado ninguna información de como poder crear un fichero a partir de un binario. Estaba intentado decodificar el contenido para ver si podía ir comprobando que contenía los datos de la tabla del ranking con:

`self.assertIn(collection, response.content.decode('utf-8'))
...`

Pero a la hora de decodificar el binario para ver el contenido me sale este error:

` UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 18: invalid start byte`

No se como encontrar el error que dice que hay en la posición 18.

**Comment by Tamiflu9** [comment]
> Si pasas tu `request` a la función de Iker es verdad que se realizarán las mismas validaciones, pero entonces tienes que detectar cuando la función de Iker devuelve errores de validación para devolverlos tú también. Para comprobar que esto lo estás haciendo bien, añade en tu test de unidad una petición que tenga fechas o grupo incorrecto para verificar que está todo bien conectado.

Al final si que hago las validaciones, que al comprobar directamente metiendo mi url: `http://127.0.0.1:8000/sql/results/1/download_ranking?group=1&start=2020-09-01&end=2021-03-21` quitando o cambiando algún dato daba fallo y no un mensaje de error, pero ya lo ha cambiado, valido los datos y he comprobado que salen los mensajes de error que deberían.

**Comment by emartinm** [comment]
> Al final si que hago las validaciones, que al comprobar directamente metiendo mi url: `http://127.0.0.1:8000/sql/results/1/download_ranking?group=1&start=2020-09-01&end=2021-03-21` quitando o cambiando algún dato daba fallo y no un mensaje de error, pero ya lo ha cambiado, valido los datos y he comprobado que salen los mensajes de error que deberían.

Perfecto, si está en el test de unidad así seguro que nunca se nos pasa.

**Comment by Tamiflu9** [comment]
> > `response.content` como bien se ve en tu prueba es un binario con el contenido del Excel. Tendrías que ser capaz de crear un objeto "fichero excel" de tu biblioteca a partir de ese binario (idealmente sin volcarlo en un fichero local en el disco duro para no dejar basura).
> 
> No he encontrado ninguna información de como poder crear un fichero a partir de un binario. Estaba intentado decodificar el contenido para ver si podía ir comprobando que contenía los datos de la tabla del ranking con:
> 
> `self.assertIn(collection, response.content.decode('utf-8')) ...`
> 
> Pero a la hora de decodificar el binario para ver el contenido me sale este error:
> 
> ` UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 18: invalid start byte`
> 
> No se como encontrar el error que dice que hay en la posición 18.

respecto a esto sigo atascada..

**Comment by emartinm** [comment]
¿Qué biblioteca usas? ¿Cómo se crea un objeto "fichero excel" en esa biblioteca? ¿Qué constructores tiene esa clase?

**Comment by Tamiflu9** [comment]
Uso `openpyxl`. Para crear un fichero hay que crear un a hoja de trabajo, activarla y luego ya escribir y guardar los datos que quieras en el fichero temporal:
```
file = tempfile
file.mkstemp()

wb = openpyxl.Workbook()
ws = wb.active

data = soup.find_all("h2")
for i in data:
     ws.cell(row=row, column=col, value=i.string)
     row += 1
...

wb.save(file.gettempprefix())
```
Con constructores no se si te refieres a esto: https://openpyxl.readthedocs.io/en/stable/api/openpyxl.workbook.workbook.html , sol las funciones que uso del modulo `Workbook` de la biblioteca

**Comment by emartinm** [comment]
Parece que lo más sencillo será volcar los bytes a un fichero binario temporal, cargarlo con https://openpyxl.readthedocs.io/en/stable/tutorial.html?highlight=load_workbook#loading-from-a-file, comprobar que las celdas están bien y borrar el temporal.

**Comment by Tamiflu9** [comment]
Vale voy a probar esto, gracias.
