### ISSUE TITLE
Tarea podio (dificultad baja)

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#36]
Tarea para @ivarui01 

Al mostrar un problema, mostrar un "podio" con el primer alumno en resolver ejercicio, el segundo y tercero.

**Comment by ivarui01** [comment]
¿Dónde debería crear el podio? ¿Dentro de cada ejercicio junto con el enunciado, las tablas, etc? ¿O antes de entrar a un ejercicio que aparezca un botón para ver el podio y te lleve a una vista diferente? Aunque de esta manera lo veo muy "separado" del ejercicio en si y tal vez no es buena idea.

**Comment by jcorreas** [comment]
En mi opinión no-técnica, creo que sería buena idea que apareciera en la lista de ejercicios, pero no como un botón, sino como tres columnas con los datos a la vista, para que los vea todo el mundo que vaya a resolver algún ejercicio. Si la idea es que los alumnos compitan, lo mejor es ver la lista de ejercicios y de un vistazo los que tienen y no tienen podio, para irse de cabeza a uno que no tiene podio todavía y ponerse a resolverlo para aparecer ahí para todos los demás. Si hay que pinchar, pues queda un poco deslucido, porque lo que mola es que todo el mundo vea el podio aunque no quiera :-).

Es posible que no quede bien o que haya un motivo técnico que no lo recomiende.

**Comment by ivarui01** [comment]
Pero entonces pondría el podio con las tres personas que lo han resuelto en el listado de ejercicios, mostrando un podio para cada ejercicio. ¿Eso no ocuparía demasiado espacio? No se si te estoy entendiendo bien.

**Comment by jcorreas** [comment]
Sí, esa es la idea. En la página de problemas (adjunto pantallazo del servidor de Enrique al final) añadiría a la derecha tres columnas con los identificadores de los tres primeros, haciendo un poco más pequeña la columna del nombre del problema. De las personas se podría dejar el identificador que ocupe menos y que aparezca más info (no sé si el nombre o algo así) cuando se pone el ratón encima. Pero no sé cómo quedará. 

Incluso si queda muy apretado, se pueden poner iconos de medallas y el nombre al pasar el ratón. Enrique, ¿qué te parece?

![lsql-listado-problemas](https://user-images.githubusercontent.com/12998415/110206518-7ba01580-7e7e-11eb-9da9-bf2d5af083e0.png)

**Comment by emartinm** [comment]
La idea de Jesús de mostrar el podio como 3 nuevas columnas me parece bastante visual. ¿Podrías hacer una prueba rápida con datos falsos y mostrarnos una captura de pantalla a ver cuánto ocupa? Si eso no nos convence, mi segunda opción sería mostrar el podio como una tabla en la página del enunciado o usar medallas que muestren el nombre, como dice Jesús.

Lo de tener que dar a botones me gustaría menos

**Comment by ivarui01** [comment]
Así yo creo que queda bien, es que en el primer mensaje no te entendí bien con lo de "columnas". En el texto de cada columna, ¿Lo dejo como Primero, Segundo y Tercero o pongo Oro, Plata y Bronce?
![image](https://user-images.githubusercontent.com/61693814/110239146-da7c9200-7f45-11eb-9ecf-09cce1993ce0.png)

**Comment by emartinm** [comment]
Es posible que se entienda mejor si además del texto se añade un icono de medallita en esa columna. @iburgoa13 añadió una biblioteca con iconos, y de ahí podrías sacar alguno: https://fontawesome.com/icons?d=gallery&p=2&q=medal. Sobre "Primero" u "Oro" yo no lo tengo claro, quizá @jcorreas lo tiene más claro. ¿Quizá se puede compactar como "icono medallita 1", "icono medallita 2", "icono medallita" 3.

Lo que quizá mejore un poco es resaltar las celdas de esas columnas con un color de fondo diferente, para que se note visualmente que son otra cosa. Por un lado la colección y el número de envíos, y por otro (con un color de fondo ligeramente diferente) el podio.

**Comment by ivarui01** [comment]
![image](https://user-images.githubusercontent.com/61693814/110337739-8c8b8b00-8026-11eb-9996-7c13da98aa2c.png)

**Comment by emartinm** [comment]
Personalmente, como usuario, entiendo peor el tick de colores. En mi anterior mensaje me refería a un icono de medalla que se vea bien que es una medalla (no sé si admite colores)

**Comment by ivarui01** [comment]
El problema es que el icono de la medalla no me carga bien y me sale una interrogación.

**Comment by ivarui01** [comment]
![image](https://user-images.githubusercontent.com/61693814/110353013-dd0ae480-8036-11eb-86c4-3f693d951896.png)

**Comment by emartinm** [comment]
@iburgoa13 carga el icono de ayuda para el ranking y le aparece bien, entiendo yo que podrás cargar cualquier otro icono de la misma biblioteca de la misma manera. ¿Es posible que estés cargando el mismo icono de ayuda en lugar de la medalla?

**Comment by ivarui01** [comment]
El icono de "?" que he pasado es lo que muestra cuando el icono no carga bien, me pasa con algunos otros también

**Comment by emartinm** [comment]
¿Puedes mostrarme el código de cómo cargas los iconos? Por si veo algo que te sirva de ayuda. Como no he usado nunca estos iconos no sé cuánto podré ayudar, a lo mejor Iker te puede dar alguna pista.

**Comment by ivarui01** [comment]
En la primera captura esta el código con el icono del tick que funciona, pero si lo cambio por el de la medalla que está en la tercera captura, no me carga bien y me muestra "?". Con otros como https://fontawesome.com/icons/award?style=solid también me pasa.
![image](https://user-images.githubusercontent.com/61693814/110363463-e5691c80-8042-11eb-8e22-7abc4c0ffa36.png)
![image](https://user-images.githubusercontent.com/61693814/110363522-f580fc00-8042-11eb-8f93-d763d24e01a3.png)
![image](https://user-images.githubusercontent.com/61693814/110363812-4e509480-8043-11eb-83ce-e30259315109.png)

**Comment by emartinm** [comment]
¿Has revisado esta lista de comprobaciones: https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting?

**Comment by emartinm** [comment]
A lo mejor hay que cargar una versión más nueva: https://cdnjs.com/libraries/font-awesome

**Comment by ivarui01** [comment]
Ya me funciona, era la versión si.
![image](https://user-images.githubusercontent.com/61693814/110524558-d7370100-8113-11eb-8e5a-bc8acc711415.png)
![image](https://user-images.githubusercontent.com/61693814/110524676-f9c91a00-8113-11eb-8c8b-e19ec6be75cf.png)
