### ISSUE TITLE
Tarea nuevo tipo de problema de encontrar BD que invalida una consulta (dificultad alta)

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#51]
Crear un nuevo tipo de problema en el que se dispone de una sentencia SQL incorrecta pero que está devolviendo los valores adecuados para un caso concreto, y el objetivo es que el usuario indique los `INSERT` necesarios para que esa consulta genere resultados incorrectos. Otra enfoque sería dar dos consultas SQL y pedir al estudiante qué datos tendrían que tener las tablas para que los resultados fueran diferentes.

 **Importante:** intentar reutilizar al máximo los métodos de oracle_driver y no tener que tocar nada en ese modulo.

Ejemplo sencillo:

Tarea: encontrar los clubes de más de 1000 socios
Consulta errónea: `SELECT * FROM Club;`
Base de datos que donde es correcta: una donde todos los clubes tienen más de 1000 socios
Base de datos donde se hace incorrecta: `INSERT INTO Club ('Alcoyano', ..., ..., 500)`

**Comment by Dashito14** [comment]
Vale, a ver si lo entiendo. El enunciado para el alumno sería algo del tipo:

Dada la **base de datos** _(Se mostraría una tabla como esta)_:

![image](https://user-images.githubusercontent.com/48255774/112634809-55e1ad00-8e3b-11eb-8443-480f4a3a6410.png)

Se pide que se encuentren los `Club` con más de 1000 `Socios`. La respuesta dada fue:

`SELECT * FROM Club;`

Aunque en este caso sea correcto, ¿nos puedes indicar que datos habría que introducir en la tabla para no fuera correcto?

Y ya después de eso el alumno tendría que insertar su respuesta que sería algo del tipo:

`INSERT INTO Club ('Real Madrid', 500)`

**Comment by Dashito14** [comment]
Obviamente la tabla es una de ejemplo hecha en Excel que no tiene el formato de una **base de datos** ya que el nombre de la columna sería `Nombre` o algo así y la tabla sería `Club`, no la columna sería Club.

**Comment by emartinm** [comment]
Exacto, ese sería un ejemplo de problema de este tipo. En el modelo se almacenaría la consulta buena `SELECT * FROM Club WHERE Socios > 1000` (posiblemente no se llegue a enseñar al usuario) y la mala `SELECT * FROM Club`. Cuando llegue un envío se comprueba que con esa BD la consulta mala y la buena dan resultados diferentes.

**Comment by Dashito14** [comment]
Una respuesta buena sería:

```
INSERT INTO Club ('Real Madrid', 1010)
INSERT INTO Club ('FC Barcelona', 500)
```

O esto no, si esto es válido se complica la solución creo yo.

**Comment by emartinm** [comment]
Sí, para este ejemplo concreto cualquier BD que tenga un club con <= 1000 socios será una respuesta válida del usuario, porque hará que 

    SELECT * FROM Club;

y

    SELECT * FROM Club WHERE Socios > 1000;

den resultados diferentes.

**Comment by Dashito14** [comment]
Osea que pueden pasar todos los INSERT que les de la gana ¿no? ¿Si hacen 80 INSERT pero uno está bien será CORRECT?

**Comment by emartinm** [comment]
El número de inserts se debería poder controlar con `min_stmt` y `max_stmt` para que tampoco se pasen :-)

Una vez dentro de estos límites, a la hora de corregir no importa el número de INSERTS porque vas a hacer lo mismo:

1. Creas las tablas (hay un método que ya hace eso)
2. Ejecutas todos los INSERT que haya puesto el usuario (mismo método que antes)
3. Compruebas que los resultados de los SELECT son diferentes (hay métodos para ejecutar SELECT)

Entre las cosas que no se nos pueden olvidar es implementar la importación de este nuevo tipo de problema desde un fichero ZIP.

**Comment by Dashito14** [comment]
Un aspecto que ahora puede ser un poco secundario pero, ¿cómo queremos que se llame este tipo de problemas?

Sí, esos tres pasos son los que había pensado en hacer.

**Comment by emartinm** [comment]
- Position: posición del problema en su colección, para mostrarlos en ese orden
- check_order (bool): indica si hay que revisar la salida teniendo en cuenta el orden de las filas o no
Creo que ambos tienen sentido en este nuevo tipo de problemas.

Sobre el nombre, creo que se podrían llamar `InitialDBProblem`, `DiscriminantDBProblem` o algo así. A lo mejor se os ocurre alguno mejor @Dashito14 @jcorreas 

Para manejar un poco mejor la complejidad, quizá podríamos dividir esta tarea en dos PR:

1. Añadir los problemas campo a campo, que se muestren bien en el juez y el administrador y que se corrijan bien
2. Importar este tipo de problemas a partir de un ZIP

**Comment by Dashito14** [comment]
Ah vale, position entonces será un valor automático ¿no? No entiendo por qué check_order es relevante en este caso. Da igual el orden en el que insertes los valores ya que lo importante es que alguno de ellos cumpla con el criterio.

En cuanto a los campos del problema se me había ocurrido:

- hide_solution: la solución con el `SELECT` correcto para poder comprobar el resultado.
- fail_solution: la solución que se muestra al usuario, la cual no sería la correcta para todos los casos.
- solution: para comprobar la solución.

En un principio esos, aparte de los de `Problem`. El nombre de `DiscriminantDBProblem` me gusta.

Dividirlo en dos PR me parece buena idea, creo que así me puedo esquematizar y focalizar más por orden.

¿Creéis que se deba mostrar el resultado de pasar la consulta por la base de datos inicial? Me refiero, en el ejemplo que estamos poniendo, mostrar el resultado de pasar la consulta `SELECT * FROM Club` a la base de datos. Personalmente no creo que fuera necesario, pues no es ninguna especie de base de datos esperada o algo así.

**Comment by emartinm** [comment]
`position` no es automático, porque si no generaría el mismo ordenamiento que PK. Es un campo que el profesor puede meter a mano por si se ha olvidado un problema anterior y que tiene un valor por defecto si no pone nada.

Los campos que indicas me parecen los necesarios. Aunque los cambiaría el nombre:
- `correct_query`: la solución con el SELECT correcto para poder comprobar el resultado.
- `incorrect_query`:  la solución que se muestra al usuario, la cual no sería la correcta para todos los casos.
- `solution` **no entiendo para qué necesitas este campo** Me puedes dar un poco más de información?

> ¿Creéis que se deba mostrar el resultado de pasar la consulta por la base de datos inicial? Me refiero, en el ejemplo que estamos poniendo, mostrar el resultado de pasar la consulta `SELECT * FROM Club` a la base de datos. Personalmente no creo que fuera necesario, pues no es ninguna especie de base de datos esperada o algo así.

Como retroalimentación puede ser interesante. En este tipo de problemas no es trivial dar información útil. Cuando haces un envío y fallas, es porque ambas consultas devuelven el mismo resultado con la BD que has introducido. ¿Qué te puede ayudar a mejorar tu BD inicial? ¿Ver lo que ha devuelto la consulta errónea con tu BD inicial es relevante? Creo que sí, pero no sé si se podría añadir algo más. @jcorreas tú qué piensas?

**Comment by Dashito14** [comment]
Podemos hacer eso. El feedback cuando fallas que sea lo que devuelve la consulta errónea. ¿Estos problemas solo se van a dar con consultas SELECT? Si es así el feedback también podría ser lo que devuelve la consulta errónea y lo que se esperaría que devolviese esa base, ¿no?

Está bien, cambio lo de los nombres, por eso los digo por aquí para que me confirméis nombres y tal :D

**Comment by emartinm** [comment]
Sí, yo por ahora me centraría en problemas de generar la BD para consultas SELECT. Se podría pensar también en funciones/procedimientos/disparadores erróneos, pero eso ya es harina de otro costal. 

No entiendo tu frase "y lo que se esperaría que devolviese esa base". Si una solución a este tipo de problema es incorrecta quiere decir que ambas consultas devuelven lo mismo para esa BD, no? Es decir, no hay una noción de "lo que debería devolverse"

**Comment by jcorreas** [comment]
> 
> > ¿Creéis que se deba mostrar el resultado de pasar la consulta por la base de datos inicial? Me refiero, en el ejemplo que estamos poniendo, mostrar el resultado de pasar la consulta `SELECT * FROM Club` a la base de datos. Personalmente no creo que fuera necesario, pues no es ninguna especie de base de datos esperada o algo así.
> 
> Como retroalimentación puede ser interesante. En este tipo de problemas no es trivial dar información útil. Cuando haces un envío y fallas, es porque ambas consultas devuelven el mismo resultado con la BD que has introducido. ¿Qué te puede ayudar a mejorar tu BD inicial? ¿Ver lo que ha devuelto la consulta errónea con tu BD inicial es relevante? Creo que sí, pero no sé si se podría añadir algo más. @jcorreas tú qué piensas?

Yo creo que sí estaría bien poner la solución con la BD inicial. En consultas muy sencillas se ve fácilmente, pero en consultas complejas (anidadas, outer joins, etc) hay que ejecutar la consulta para ver lo que sale, no es nada trivial. Si le damos el resultado le estamos dando más facilidades sin resolver el problema, que lo tiene que hacer el alumno.

**Comment by Dashito14** [comment]
Se me ha olvidado, el campo `solution` es para poder pasar las bases de datos con esa query. Quizás se puede hacer automáticamente pero como no lo sé pensaba en guardar la solución del alumno en una variable, pasarle la base de datos y después las dos **query** a ver como quedaba.

> No entiendo tu frase "y lo que se esperaría que devolviese esa base". Si una solución a este tipo de problema es incorrecta quiere decir que ambas consultas devuelven lo mismo para esa BD, no? Es decir, no hay una noción de "lo que debería devolverse"

Tienes razón, estaba pensándolo ahora y es verdad que no le podemos mostrar lo que esperamos que se devuelva. El feedback sería la tabla con el resultado que ha dado y diciendo que es incorrecto, ¿no?


> Yo creo que sí estaría bien poner la solución con la BD inicial. En consultas muy sencillas se ve fácilmente, pero en consultas complejas (anidadas, outer joins, etc) hay que ejecutar la consulta para ver lo que sale, no es nada trivial. Si le damos el resultado le estamos dando más facilidades sin resolver el problema, que lo tiene que hacer el alumno.

De acuerdo, ponemos algo del estilo "**Base de datos resultante**" o algo así. Con un nombre mejor en el que se especifique que es el resultado de pasar la base de datos inicial por la query errónea.

**Comment by jcorreas** [comment]
> Tienes razón, estaba pensándolo ahora y es verdad que no le podemos mostrar lo que esperamos que se devuelva. El feedback sería la tabla con el resultado que ha dado y diciendo que es incorrecto, ¿no?

Yo creo que sí. No les podemos dar más ayuda, les resolveríamos el problema. 

> De acuerdo, ponemos algo del estilo "**Base de datos resultante**" o algo así. Con un nombre mejor en el que se especifique que es el resultado de pasar la base de datos inicial por la query errónea.

Mejor "**Resultado de la consulta**". Al menos inicialmente no hay duda sobre la BD sobre la que se ejecuta la consulta, que es la BD inicial. Y si intenta con un insert y sigue sin conseguir resolver el ejercicio, el título "resultado de la consulta" sigue siendo válido para esa BD extendida con el insert.

**Comment by emartinm** [comment]
La solución del alumno te llegará en la petición y la puedes usar como una varible. No se debe almacenar en la BD del juez dentro del problema (porque habrá muchos envíos), pero sí dentro del objeto Submission que se genere (como pasa ahora, creo que no hay que cambiar nada).

Por lo demás, estoy de acuerdo con lo que habéis dicho :-)

Es verdad que la retroalimentación es diferente a lo esperado, pero lo único que tenemos para mostrar es el resultado de la consulta mala con su BD inicial que el usuario ha proporcionado. Y el mensaje a mostrar debe ser "Tu base de datos no permite descubrir el error en la consulta" o algo similar.

**Comment by Dashito14** [comment]
Al intentar crear un problema me sale este error 
![image](https://user-images.githubusercontent.com/48255774/113598647-bc39ad00-963d-11eb-8609-be3406412ce2.png)
No sé si se debe a algo que he tocado, pero he estado buscando y es que no sé que es.

**Comment by jcorreas** [comment]
Yo creo que no es un error, me parece que es un mensaje informativo. ¿No salía antes?

**Comment by Dashito14** [comment]
Pues la cosa es que no lo sé, pero al crear el problema se queda cargando y nunca llega a saltar un error en la página y en la consola solo me sale ese mensaje. No sé qué puede estar pasando.

**Comment by emartinm** [comment]
Como bien dice @jcorreas es un mensaje informativo que indica que se ha conectado correctamente con Oracle en localhost:1521. No sé dónde se puede estar quedando parado, trata de depurar paso a paso (o pon prints) a ver en dónde se está quedando atascado. Entiendo que si antes no lo hacía y ahora no, será algún tipo de interacción más o menos compleja con el código que hayas incorporado. Pero es necesario saber dónde lo está haciendo.

**Comment by Dashito14** [comment]
Pues es que no me va ni recién clonado. Acabo de probar a bajármelo de nuevo y tampoco me carga los problemas. He probado a pasar los test y tampoco me van, se quedan colgados.

![image](https://user-images.githubusercontent.com/48255774/113750267-e311e500-970a-11eb-8295-63efb7b69d6c.png)

Aquí por lo menos parece que es algo del datetime pero cuando yo lo subí esto iba perfectamente, no sé si algún commit de después puede estar dando problemas con esto.

**Comment by emartinm** [comment]
Ese warning por las timezones lleva con nosotros tiempo, y no causaría cuelgues. Si no te funciona ni con un clon nuevo, podría ser que la BD Oracle de tu sistema esté dando problemas. Intenta detectar exactamente en qué instrucción se queda colgado, y revisa que puedes usar la BD Oracle desde SQLDeveloper para confirmar que sigue funcionando.

**Comment by Dashito14** [comment]
Esto es lo máximo que he podido sacar para el test

![image](https://user-images.githubusercontent.com/48255774/113874419-11003380-97b6-11eb-9cea-0253e01ace57.png)

Falla en `cursor.execute(create_script)`. El print de AQUI ENTRA ANTES sí que se muestra, el otro no. 
Línea 365 de **oracle_driver.py**, en la función **create_user**.
Esto no creo que tenga que ver con lo de agregar problemas pero por lo visto es algún fallo con Oracle.

¿Cómo se hace para restaurar la contraseña por si acaso?

**Comment by emartinm** [comment]
Pues está claro que es algo con Oracle, porque es justo al ejecutar un script SQL para crear el usuario. Imprímete por pantalla el contenido de `create_script` y ejecútalo a mano desde SQLDeveloper, a ver si te da algo más de información. No es un problema de `cx-Oracle` porque llevamos con la versión 8.1.0 bastante tiempo. A lo mejor puede ser algo relacionado con el Oracle Instant Client (¿que ya no esté en el PATH o algo así? aunque de eso se queja).

> ¿Cómo se hace para restaurar la contraseña por si acaso?

Pues la verdad que no lo sé, siempre lo busco en Internet. Básicamente es entrar con la cuenta de ADMIN y la contraseña que pusieras durante la instalación y ejecutar un ALTER USER (creo) para cambiar la contraseña.

**Comment by Dashito14** [comment]
Esto es lo que tengo en create_script

![image](https://user-images.githubusercontent.com/48255774/113895489-524e0e80-97c9-11eb-8f7e-e8477c5ddedf.png)

Así se queda SQL Developer

![image](https://user-images.githubusercontent.com/48255774/113895540-5f6afd80-97c9-11eb-886a-60588b77601a.png)

Lleva 15 minutos en bucle sin llegar a hacer nada.
En el PATH sí que está el Oracle Instant Client, y he buscado el PATH que estaba puesto y efectivamente sigue estando ahí.

**Comment by emartinm** [comment]
¿Puede ser que tengas alguna conexión abierta que ha hecho cambios en la BD y que por eso esté bloqueando todas las demás? ¿Puedes cerrar completamente tu BD Oracle, volver a arrancar y probar con ese mismo _script_? Por si acaso cambia el nombre de usuario y la clave. También puedes probar a hacer algo tonto como

    SELECT * FROM DUAL;

A ver si eso funciona. En el peor de los casos podrías desinstalar completamente tu BD Oracle y volver a instalarla.

**Comment by Dashito14** [comment]
Ya está. He forzado el cierre de todo lo relacionado con Oracle, lo he vuelto a abrir y ya parece que funciona. Antes de hacer esto había probado la sentencia que me has pasado y esa sí que funcionaba.

Lo de los problemas también está solucionado. 👯‍♂️

**Comment by emartinm** [comment]
¡Genial! Puede que haya sido una conexión abierta sin su COMMIT reglamentario que impedía hacer otros cambios como crear usuarios. Me alegro de que se resolviera de manera sencilla. Algo hemos aprendido: en caso de problema raro con Oracle, cerrar todo y volver a abrir :-)

**Comment by Dashito14** [comment]
La vista del problema
![image](https://user-images.githubusercontent.com/48255774/113996660-ab648380-9857-11eb-8ada-638f4c718ef5.png)

La vista en **admin** al agregar

![Uploading image.png…]()

La vista en **admin** al ver todos los problemas

![image](https://user-images.githubusercontent.com/48255774/113996793-ca631580-9857-11eb-9e9a-2f73b0edc82d.png)

**Comment by emartinm** [comment]
Visualmente lo veo bien. Lo único la frase "SENTENCIA DE LLAMADA A LA BASE DE DATOS", que la pondría en minúsculas como el resto de títulos. Y como se trata de la consulta errónea, pondría algo más específico como "Consulta SQL errónea" o "Consulta SQL errónea a depurar". No sé si a @jcorreas se le ocurre alguna frase mejor, yo nunca termino convencido del todo con lo que propongo :)

**Comment by Dashito14** [comment]
Yo os lo he puesto por lo mismo, lo he puesto yo sin pensar esperando a que me dijerais algo mejor, que siempre tenéis mejores ideas.

**Comment by jcorreas** [comment]
Creo que lo mejor es la última opción: "Consulta SQL errónea a depurar". Seguramente cuando estemos revisando la aplicación en conjunto se nos ocurrirán frases mejores, pero por ahora esta es la que se ajusta más.

**Comment by Dashito14** [comment]
¿Cómo veis esta retroalimentación?

![image](https://user-images.githubusercontent.com/48255774/114176797-f2c44000-993b-11eb-9e14-033c0c89b380.png)

**Comment by jcorreas** [comment]
Me parece bien, no hay mucho más que se pueda decir sobre esto.

No sé exactamente a lo que te refieres con el orden. Creo que en este tipo de problemas el orden de los insert del alumno nunca es importante, ni siquiera teniendo en cuenta que la consulta a depurar tenga un ORDER BY. De hecho, es posible que haya consultas erróneas con ORDER BY incorrecto que sean interesantes como problema.  Pero esto no afecta al orden de los inserts.

**Comment by Dashito14** [comment]
Justo eso. Al principio estuvimos hablando y decidimos que el orden sería importante ya que hay un campo que se llama `check_order` que debía incluirle, pero al hacer la retroalimentación no se me ha ocurrido ningún supuesto en el que pudiera ser relevante. 

El orden es del resultado, no de los **insert**, creo.

**Comment by jcorreas** [comment]
No recuerdo lo que hablamos de check_order, supongo que @emartinm te puede ayudar más en ese tema.

Lo que sí hay que tener en cuenta es que hay que comprobar que los inserts cuando se ejecuten no produzcan errores. Por ejemplo, si se introduce una fila con un valor de la clave primaria que ya existe.

Y en este tema de los errores sí que hay operaciones que dependen del orden.  Por ejemplo, si se tienen que introducir inserts de varias tablas y hay una clave externa que las relaciona, se deben insertar primero las filas de la tabla referenciada. Por ejemplo, si hay una clave externa FK_codPostal en la tabla de clientes que referencia la tabla de códigos postales: no se puede insertar un cliente antes de haber insertado el CP en el que vive ese cliente.

Pero en mi opinión no debes profundizar en el detalle de estos problemas: solo debes detectar si se produce algún error al ejecutar las sentencias INSERT y mostrarlo al usuario. @emartinm, qué te parece?

**Comment by emartinm** [comment]
El orden sería importante en los ejercicios de consulta SQL que involucren orden. Por ejemplo, si se pide "los clubes ordenados por número de socios ascendente" y la consulta errónea es `SELECT * FROM Club ORDER BY Nombre ASC` entonces deberíamos indicar que la siguiente solución es correcta porque destapa diferencias entre la consulta errónea y la correcta (`SELECT * FROM Club ORDER BY Num_socios ASC`):

    INSERT INTO Club VALUES ("VCF", Valencia, 3000);
    INSERT INTO Club VALUES ("ARS", Londres, 4000);

Si no tenemos en cuenta el orden a la hora de comparar los resultados entre la consulta errónea y válida, la consulta incorrecta y la correcta siempre generarán los mismos resultados (todas las filas de la tabla) y por tanto nunca podremos superar este ejercicio :-)

**Comment by emartinm** [comment]
Sí, si los INSERT del usuario generan errores habría que capturarlo y mostrárselo al usuario como un error en tiempo de ejecución, al igual que en los ejercicios DML

**Comment by Dashito14** [comment]
Os dejo capturas de cómo es un problema entero en el que se tiene en cuenta el orden.

![image](https://user-images.githubusercontent.com/48255774/114272236-a5b49c80-9a15-11eb-8f8b-94614572f6ca.png)
**----------------------------------------------------------------------------------------------------------------------------------------**
**----------------------------------------------------------------------------------------------------------------------------------------**
**----------------------------------------------------------------------------------------------------------------------------------------**
![image](https://user-images.githubusercontent.com/48255774/114272238-a8af8d00-9a15-11eb-9d0c-8edcac98c107.png)
**----------------------------------------------------------------------------------------------------------------------------------------**
**----------------------------------------------------------------------------------------------------------------------------------------**
**----------------------------------------------------------------------------------------------------------------------------------------**
![image](https://user-images.githubusercontent.com/48255774/114272239-ac431400-9a15-11eb-8097-dad1a854b2e7.png)

**Comment by Dashito14** [comment]
Creo que con esto ya estarían hechos todos los casos del problema. Si lo veis bien claro.

**Comment by Dashito14** [comment]
Bueno 6 horas después y después de hacer los test y varias pruebas me acabo de dar cuenta de que estaba al revés, en los casos que he pasado al hacer `INSERT INTO Club VALUES ('...', 'Alcoyano', '...', 5000)` debería de dar resultado correcto porque se demuestra que ordenar por **Nombre** no es lo correcto. Ya está corregido.

**Comment by Dashito14** [comment]
No sé si has introducido alguna actualización en pylint, pero no se puede pasar de 1000 líneas en los archivos, y en el de `test_views.py` he añadido los nuevos test y me paso. ¿Dónde tengo que poner estos test?

**Comment by Dashito14** [comment]
He conseguido que se carguen los archivos desde un ZIP también mientras espero, porque creo que la tarea ya está acabada. Lo que no sé es muy bien como hacer los test para comprobar lo del ZIP, he estado viendo ejemplos pero no los encuentro dónde están dentro del proyecto.

**Comment by emartinm** [comment]
La retroalimentación "Tu resultado no se muestra en el orden correcto" no sé si es adecuada en un problema de este tipo. Porque una solución a un problema de este tipo está mal cuando no es capaz de sacar a relucir el error en la consulta, es decir, diferenciar la consulta incorrecta de la correcta. En otras palabras, la retroalimentación debería explicar que la solución es incorrecta porque los datos de la BD no permiten detectar un comportamiento erróneo en la consulta propuesta (y que está mal). En el ejemplo que pones, añadir (Alcoyano, 500) haría que el resultado esté ordenado por número de socios ascendente, así que esa solución debería ser rechazada y (Alcoyano, 5000) sí que permitiría discriminar entre la consulta errónea y la correcta.

Para redistribuir los tests de vistas y hacer ficheros más pequeños, movería los métodos que sirven para ver que las peticiones HTTP a `judge:submit` devuelven los códigos esperados. Es decir, crearía un nuevo fichero `test_submit.py` y movería los métodos `test_compile_error()`, `test_plsql_correct()`, `test_validation_error()`, `test_select_no_output()`, **además de los nuevos tests que hayas hecho y que permiten comprobar el funcionamiento de `submit` para el nuevo tipo de problema**.

Por organizarme yo, prefiero que hagas un PR únicamente del nuevo tipo de problema y su corrección, y luego otro con la lectura de este tipo de problema desde un fichero ZIP. Porque para el segundo PR habrá varios casos de prueba (faltan ficheros, los contenidos de los ficheros no son los esperados, etc.) y prefiero no tenerlo todo en la cabeza mientras reviso el PR.

**Comment by Dashito14** [comment]
Justo acabo de hacer todos los test con los archivos zip. No pasa nada, me lo copio en otro repositorio. 

Cambio lo de la retroalimentación, pongo para cualquier caso:
**La inserción que has propuesto no permite detectar el comportamiento erróneo de la sentencia.**

**Comment by emartinm** [comment]
Acabo de aceptar el PR así que las conversaciones se han cerrado. Si puedes, envíame por aquí los datos del problema discriminante que has usado para hacer las pruebas de retroalimentación que has adjuntado y que siempre salía columna=1 y línea=1.

**Comment by Dashito14** [comment]
```
INSER INTO Club VALUES ('a', 'a', 23)
INSERT Club VALUES ('a', 'a', 23)
INSERT INTO Club VALUES ()
INSERT INTO Club VALUES ('a', 'a', 'a')
```

Estas son las que he probado.

**Comment by Dashito14** [comment]
¿Me pongo con lo de los ZIP o espero a que hagas el 100%? En un principio ya lo tengo hecho así que sería incluir los cambios al nuevo repositorio y hacer el PR.

**Comment by emartinm** [comment]
Ya puedes ponerte con el ZIP, acabo de subir cambios para conseguir el 100% y recuperar la columna y línea en la retroalimentación.
