### ISSUE TITLE
Detalles logros

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#54]
- ¿Poner el icono de trofeo de los logros en color oro como las medallas? Creo que esto lo comentamos en algún momento, pero no estoy seguro
- Incluir el nombre de usuario en la página que muestra los logros, ya que cuando ves la de otra persona es muy fácil perderse. Básicamente es añadir una cabecera que diga `"Lista de logros de <usuario>"`

@Dashito14 , ¿te puedes encargar tú? Si no avísame y lo cambio yo, pero no quería tocar nada de tu código sin avisar.

**Comment by emartinm** [comment]
Lo del color era un problema en el despliegue, que no había actualizado el nuevo CSS. Ya está arreglado en el servidor.

**Comment by Dashito14** [comment]
Me puedo encargar.

**Comment by Dashito14** [comment]
![image](https://user-images.githubusercontent.com/48255774/112754198-4ac58300-8fdb-11eb-9d27-13a17654b28e.png)

¿Así o en minúscula como lo has escrito tú?

**Comment by emartinm** [comment]
Como los nombres de usuario tal cual los saco de GEA estarán en minúsculas, quizá mejor ponerlo en minúscula. Y como no es una lista sino dos, quizá mejor:

    Página de logros de <usuario>

quizá resaltando el nombre de usuario con negrita o algo similar

**Comment by Dashito14** [comment]
Vale, lo hago ahora y hago PR para esto
