### ISSUE TITLE
Tarea soporte multi-idioma (dificultad alta)

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#62]
Añadir soporte multi-idioma al juez y una versión completa en inglés. Esta tarea se puede dividir en varias fases:

1. Añadir suporte multi-idioma para las páginas generadas según el idioma configurado en el navegador del usuario o forzado manualmente por el usuario. Se recomienda realizar varios PR de tamaño manejable para no modificar muchos ficheros y minimizar colisiones con otras tareas.
2. Permitir que los problemas tengan enunciados en varios idiomas y se visualice uno u otro (un único PR).
3. Permitir que los problemas tengan BD en varios idiomas y se visualice y use para la corrección la que toque (un único PR).

**Comment by emartinm** [comment]
Revisión de las fases:
1. Añadir suporte multi-idioma al interfaz del juez para las páginas generadas, teniendo en cuenta el idioma configurado en el navegador del usuario o forzado manualmente por el usuario. Se recomienda realizar varios PR de tamaño manejable para no modificar muchos ficheros y minimizar colisiones con otras tareas.
2. Anotar con idioma a los problemas para mostrar una bandera al lado de su título. Inferir los idiomas de una colección a partir de los idiomas de sus problemas.
3. Pensar cómo dar soporte multi-idioma a los logros. Algunas alternativas serían tener varios idiomas en los nombres de los logros y usar la que toque, o usar un servicio externo de traducción para traducir al idioma destino.

**Comment by emartinm** [comment]
@ivarui01 , ahora que estoy con la página de ayuda, también sería necesario que el juez mostrase la página en español o en inglés dependiendo de qué usuario la pida, al igual que los enunciados. Espero terminarla y subirla en los próximos días. Básicamente estoy haciendo la versión española en un único fichero HTML que se renderiza como plantilla. La idea sería que incorpores la posibilidad de que si un usuario inglés pide la ayuda, se le muestre la versión de la página en inglés. **Pero no es necesario que traduzcas tú la página ayuda del español al inglés**. Puedes hacer una página *dummy* que diga `This is the help page` para probar que funciona, y luego ya nos encargaremos de traducirla completamente.

**Comment by ivarui01** [comment]
Haciendo los tests he visto un pequeño pero importante problema y es que, en muchos tests se comprueba que determinada cadena existe dentro del html, la cosa es que esos textos unas veces se comprueban en inglés:
![image](https://user-images.githubusercontent.com/61693814/115119579-6f44c780-9fa9-11eb-8f15-76f6972736e7.png)
Y otras veces en español:
![image](https://user-images.githubusercontent.com/61693814/115119730-348f5f00-9faa-11eb-9306-1f058363f1b1.png)
Entonces, ¿Debería cambiar el idioma de la aplicación en settings_shared.py a español y hacer los tests en español o traducir al ingles todos los tests?
![image](https://user-images.githubusercontent.com/61693814/115119869-d57e1a00-9faa-11eb-937a-d35008ac15fd.png)

**Comment by emartinm** [comment]
La inmensa mayoría estarán en español, así que me parece buena idea que se cambie el idioma a `es-es` para garantizar que el idioma por defecto es español de España. Los pocos mensajes que has encontrado en inglés proceden de comprobaciones de validación usando formularios, y no sé si cambiarán automáticamente al cambiar `LANGUAGE_CODE`. Si cambian, perfecto.

**Comment by ivarui01** [comment]
Si cambian

**Comment by ivarui01** [comment]
Tanto dejándolo en inglés como cambiándolo al español tengo que cambiar algunos tests, pero cambiándolo a `es-es` son menos.

**Comment by emartinm** [comment]
Me parece genial que cambien esos mensajes generados automática por los formularios de Django. Están todos relacionados con mensajes de error, ¿verdad? Si no son muchos, mejor cambia el test para que realice la comprobación con la cadena adecuada en español.

**Comment by emartinm** [comment]
Recuerda hacer un PR cuando tengas varias traducciones aplicadas pero sin que lleguen a ser demasiadas.

**Comment by ivarui01** [comment]
En principio el primer PR va a ser con traducciones en los html, son entre 1 y 6 traducciones más o menos por cada html.

**Comment by ivarui01** [comment]
Después de ese me faltarían los html grandes y las traducciones que vengan de los archivos .py

**Comment by ivarui01** [comment]
![image](https://user-images.githubusercontent.com/61693814/115123066-960bf980-9fbb-11eb-9521-f710822c594f.png)
¿Ahí estaría bien el botón para cambiar de idioma? ¿Y que texto podría poner que no fuese "Go"? He intentado poner las banderitas en vez de la palabra, o junto a la palabra, pero no he encontrado la manera de poner imágenes en un select.

**Comment by ivarui01** [comment]
Estoy teniendo un problemilla y es que al descargar un ranking, en el nombre del grupo pone "English" en vez de el nombre del grupo.
![image](https://user-images.githubusercontent.com/61693814/115124528-0cf8c080-9fc3-11eb-8e3b-6fa782b1ca75.png)
En la vista de ranking sale bien.
![image](https://user-images.githubusercontent.com/61693814/115124540-18e48280-9fc3-11eb-8e29-c1bf017e3bc3.png)
Y no se por que puede ser porque todavía no he tocado las traducciones por esta zona.

**Comment by ivarui01** [comment]
Vale, justo cuando he enviado el mensaje he pensado que tal vez sea porque al hacer el excell, para poner el nombre del grupo coge el primer elemento del select, y ahora el primer select que hay es el de los idiomas, por tanto coge el primer idioma del select.

**Comment by ivarui01** [comment]
Ya lo he solucionado cambiando `option = soup.find("option")` por `option = soup.find(id='clase').find("option")` en la función `download_ranking`

**Comment by ivarui01** [comment]
Y para los tests, ¿Me dijiste que no analizase todos los html, o que los analizase todos pero no enteros?

**Comment by emartinm** [comment]
> ¿Ahí estaría bien el botón para cambiar de idioma? ¿Y que texto podría poner que no fuese "Go"? He intentado poner las banderitas en vez de la palabra, o junto a la palabra, pero no he encontrado la manera de poner imágenes en un select.

Lo veo un poco lejos del meollo, pero tampoco veo un lugar mucho mejor. Si quieres por ahora déjalo ahí. Como no se me ocurre qué texto poner al botón lo que se podría hacer es algo parecido al CV de la UCM, que sería añadir un menú Bootstrap que te muestra el idioma actual y si lo abres ves todas las opciones disponibles (y solo con pinchar se cambia el idioma):

![Captura de pantalla de 2021-04-19 12-17-36](https://user-images.githubusercontent.com/1685343/115220967-7aaf0480-a109-11eb-96f0-1fb6f383ea0e.png)

En el CV este menú aparece en la barra al lado de los demás sin ninǵun problema, así que podrías integrarlo en la barra a continuación del menú del usuario sin ningún espacio adicional.

> Ya lo he solucionado cambiando option = soup.find("option") por option = soup.find(id='clase').find("option") en la función download_ranking

Me alegro que lo hayas solucionado, es uno de los problemas de hacer auto-scraping :-s

> Y para los tests, ¿Me dijiste que no analizase todos los html, o que los analizase todos pero no enteros?

Si no recuerdo mal, creo que dije probar "algo" de todos los HTML que tengan sentido. Es decir, si 5 vistas usan la misma plantilla, haz el test únicamente con una de ellas. Y no compruebes todo el texto, simplemente haz alguna prueba manejable, por ejemplo:
- Configurar `Client` para realizar peticiones en inglés
- Comprobar que la página resultante no contiene la frase "Error de validación"
- Comprobar que la página resultante sí contiene la frase "Validation Error"

Seguramente nos dejemos algún error fuera y nos daremos cuenta con el tiempo, pero hacer pruebas exhaustivas sería realmente matador.

**Comment by emartinm** [comment]
@ivarui01 acabo de subir la página con la ayuda del juez en español, commit ae420d935736afe56a40a73d8ada2052ac015a82. Ten cuidado que también he cambiado el menú "Resultados" por "Clasificación". 

En algún momento dentro de esta tarea deberías incorporar soporte para que se muestre esta página o una en inglés (pero no tienes que traducirla)

**Comment by ivarui01** [comment]
No he conseguido dejar el botón mas bonito. No he podido poner el estilo como el botón de al lado porque es un tipo diferente.
![image](https://user-images.githubusercontent.com/61693814/115728634-f10b6b00-a384-11eb-9af2-7d2fd1a7a500.png)
Yo lo pondría a la derecha del todo porque ahí a mi parecer no pega mucho, pero como veas.
No he podido poner las banderas porque necesito que sea un `form` con un `select` y en el `select` no las puedo poner, en el botón de al lado, el del perfil, si que lo puedo poner porque no es un `select`, pero en el de los idiomas no.
Y luego hay un problema y es que si pongo que los idiomas se muestren con el nombre de su propio idioma, hay algunos que salen con la primera letra en mayúscula y otros en minúscula y queda feo, pero si pongo que los nombres salgan en el idioma actual sale bien, pero yo creo que es mejor que salgan en su propio idioma. Si hay muchos idiomas no queda tan mal que haya algunos en mayúscula y otros en minúscula, el problema es que de momento solo hay inglés y español y cada uno se ve de una manera.
![image](https://user-images.githubusercontent.com/61693814/115729327-9fafab80-a385-11eb-87ea-3ac0a8611804.png)
![image](https://user-images.githubusercontent.com/61693814/115729422-b0f8b800-a385-11eb-8a1d-4e9f7c248cb2.png)
![image](https://user-images.githubusercontent.com/61693814/115729998-2fedf080-a386-11eb-989c-3fa02862f640.png)

**Comment by ivarui01** [comment]
Lo que puedo hacer es poner la bandera del idioma actual en cualquier sitio:
![image](https://user-images.githubusercontent.com/61693814/115732736-8a884c00-a388-11eb-9681-8eb4aa9c4b73.png)

**Comment by emartinm** [comment]
Aunque quede feo, yo dejaría que el nombre de cada idioma se muestre en ese idioma y no todos en inglés. Cada idioma tendrá sus reglas sobre cómo escribir el nombre del idioma.

Con respecto a la bandera en el desplegable tampoco me parece primordial, sobre todo viendo otros sistemas de amplio uso (como el CV) que no usan banderitas para seleccionar el idioma. Para mostrar visualmente el idioma de los problemas y de las colecciones sí que usaría banderita en lugar de texto cuando se muestre el listado.

Como comentamos que las etiquetas de idioima irían en los problemas, añadiría un método en el modelo `Collection.language()` que te devuelva el idioma si todos los problemas son de ese lenguaje. Es importante que este nuevo campo de los problemas no sea nulo y tenga como valor por defecto `es` para que no haya que establecerlo a mano en el sistema que ya está en funcionamiento.

**Comment by ivarui01** [comment]
Entonces, ¿Solo muestro bandera en las colecciones que tengan todos los problemas del mismo idioma?

**Comment by emartinm** [comment]
> Entonces, ¿Solo muestro bandera en las colecciones que tengan todos los problemas del mismo idioma?

Eso es lo que creo recordar de la reunión que tuvimos, pero por si acaso que lo confirme @jcorreas .

Pensando de nuevo sobre el menú y la imposibilidad de poner banderas, ¿por qué es necesario que el selector de idioma sea un `input` de formuario y no un menú Bootstrap como el que tiene justo a la izquierda? Sospecho que todo lo que puedas hacer con el `input` lo podrás hacer con el menú Boostrap, y además en en menú Bootstrap podrás añadir banderas y cualquier otra cosa. **Además, visualmente dará menos el cante con el menu que tiene al lado, que sí es Bootstrap.** Pongas o no banderas, creo que usar menús de aspecto uniforme es más adecuado.

**Comment by jcorreas** [comment]
> Aunque quede feo, yo dejaría que el nombre de cada idioma se muestre en ese idioma y no todos en inglés. Cada idioma tendrá sus reglas sobre cómo escribir el nombre del idioma.

Sí, lo correcto es poner cada idioma en su idioma, y que esté en mayúsculas o minúsculas según sus propias reglas.

> Con respecto a la bandera en el desplegable tampoco me parece primordial, 

De acuerdo.

> > Entonces, ¿Solo muestro bandera en las colecciones que tengan todos los problemas del mismo idioma?
> 
> Eso es lo que creo recordar de la reunión que tuvimos, pero por si acaso que lo confirme @jcorreas .

Pues no lo sé, yo creo que también fue esa la conclusión, para no saturar de banderas e iconos la lista. 

Hay tres opciones posibles: a) poner solo bandera en las colecciones con ejercicios de un idioma; b) poner bandera de todos los idiomas de cada colección (creo que es la peor, aunque es la más "neutra"); c) poner banderas de las colecciones multi-idioma, y si acaso también de las mono-idioma que no sean en español, si es que consideramos que hay un "idioma por defecto" o principal que es el español. 

Yo creo que la decisión fue la opción a, pero todavía estamos a tiempo de elegir. A mí me parece que la c es buena opción, como la a, pero entiendo que es más complicada y que podéis no estar de acuerdo.

**Comment by emartinm** [comment]
A mi la opción c) no me parece nada mal. Así se añadirían banderitas inglesas a las colecciones que estén íntegramente ne inglés, lo que ayudaría en el grupo en inglés. Y para el resto no aparecería nada. En cualquier caso, el método de `Collection` para saber qué idiomas aparecen en los problemas de una colección va a ser necesario en cualquiera de las 3 opciones.

**Comment by ivarui01** [comment]
> > Entonces, ¿Solo muestro bandera en las colecciones que tengan todos los problemas del mismo idioma?
> 
> Eso es lo que creo recordar de la reunión que tuvimos, pero por si acaso que lo confirme @jcorreas .
> 
> Pensando de nuevo sobre el menú y la imposibilidad de poner banderas, ¿por qué es necesario que el selector de idioma sea un `input` de formuario y no un menú Bootstrap como el que tiene justo a la izquierda? Sospecho que todo lo que puedas hacer con el `input` lo podrás hacer con el menú Boostrap, y además en en menú Bootstrap podrás añadir banderas y cualquier otra cosa. **Además, visualmente dará menos el cante con el menu que tiene al lado, que sí es Bootstrap.** Pongas o no banderas, creo que usar menús de aspecto uniforme es más adecuado.

También es de Bootstrap pero para un `select`, el problema es que necesito hacerlo de esta manera:
![image](https://user-images.githubusercontent.com/61693814/115877257-85d69d00-a447-11eb-97d3-fbf98d9fcef6.png)
Y sin un `form` no veo como hacerlo, he estado buscando bastante por internet y en la documentación de Django y no he encontrado nada, la única manera que aparece en la documentación de Django es así y no he encontrado nada sobre ese `{% url 'set_language' %}`

**Comment by ivarui01** [comment]
En cuanto a este código que comentaste,
```
 def language_to_flag(code):
    """ bla bla bla """
    if code.lower() == 'en':
        return 'flag-icon-us'
    else:
        return 'flag-icon-' + code.lower()
```
¿Dónde debería ponerlo? ¿En templatetags igual que cuando creaste el de los ids aleatorios para mi primera tarea?

**Comment by emartinm** [comment]
Si la limitación es únicamente hacer una petición POST, puedes manejar el evento onclick de un enlace y realizar una petición POST con JavaScript puro o con Jquery. Es más coñazo, eso seguro, así que no le dediques tiempo si no te motiva. Si quieres separar el menú de idioma a la derecha del todo para que no contraste tanto con el otro menú Bootstrap, lo entendería.

La ruta `set_language` está explicada aquí: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#set-language-redirect-view. Básicamente asigna un idioma en la sesión y crea una cookie, y redirecciona a la ruta que venga en el parámetro `next`.

> ¿Dónde debería ponerlo? ¿En templatetags igual que cuando creaste el de los ids aleatorios para mi primera tarea?

No, ahí no porque esta función no define ningún operador de plantilla. Ahora mismo no encaja en ninguno de los módulos, quizá crearía un nuevo módulo `translation.py` para esa función y otras que quizá puedas necesitar en esta tarea.

**Comment by ivarui01** [comment]
> La ruta `set_language` está explicada aquí: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#set-language-redirect-view. Básicamente asigna un idioma en la sesión y crea una cookie, y redirecciona a la ruta que venga en el parámetro `next`.

Ya, si de ahí saque el primer `select` con el botón `Go`, pero esperaba una explicación un poco mas amplia porque con esa explicación no se como usarlo sin un `form`.

**Comment by ivarui01** [comment]
> No, ahí no porque esta función no define ningún operador de plantilla. Ahora mismo no encaja en ninguno de los módulos, quizá crearía un nuevo módulo `translation.py` para esa función y otras que quizá puedas necesitar en esta tarea.

¿Y como lo uso entonces en el html?

**Comment by emartinm** [comment]
¿Lo puedes resolver fuera con una llamada a función Python y luego pasarle el nombre de la bandera como parámetro de plantilla? Si no, define la etiqueta de plantilla en `templatetags` y resuélvelo dentro.

**Comment by ivarui01** [comment]
El botón quedaría así:
![image](https://user-images.githubusercontent.com/61693814/115899711-5fbcf700-a45f-11eb-9e1c-8bbdff3d5c50.png)

**Comment by ivarui01** [comment]
¿Cómo puede ponerme esto en un test?
![image](https://user-images.githubusercontent.com/61693814/115915577-ccda8780-a473-11eb-9d34-d39fcbaad115.png)

**Comment by emartinm** [comment]
Me gusta bastante cómo queda, con el desplegable y la bandera justo al lado.

**Comment by emartinm** [comment]
Lo pongo por aquí para que no se vaya cuando se cierre el PR: indícame por favor la URL oficial de la biblioteca de banderas `flag-icon-css` para que lo enlace en la página de ayuda, junto con su licencia.

**Comment by ivarui01** [comment]
https://cdnjs.com/libraries/flag-icon-css

**Comment by ivarui01** [comment]
¿No se puede usar un tag dentro de un for? Esto me da error:
![image](https://user-images.githubusercontent.com/61693814/116130585-b2025000-a6cb-11eb-96c4-060e2c36efa0.png)
![image](https://user-images.githubusercontent.com/61693814/116130676-cc3c2e00-a6cb-11eb-9090-bdda181f266a.png)

**Comment by emartinm** [comment]
Me resulta extraño porque dentro de los bucles se puede usar cualquier etiqueta definida... Has importado la etiqueta con `{% load loquesea %}`, ¿no?

Por otro lado, actualiza tu ramas porque las vistas han cambiado algo al usar únicamente Bootstrap-icons y Bootstrap 5. Concretamente en la versión actual ya no se usa tick.svg.

**Comment by ivarui01** [comment]
He importado la etiqueta si. No se que estaré haciendo mal.

**Comment by emartinm** [comment]
> He importado la etiqueta si. No se que estaré haciendo mal.

Pero otras etiquetas predefinidas sí que las puedes utilizar, ¿no? ¿Y si lo pones fuera del bucle sí que funciona?

No sé si será por algo que he cambiado al adaptar la interfaz a Bootstrap 5, pero cuando la ventana se hace pequeña el menú de opciones se termina colapsando en un botón de 3 líneas pero el selector de idioma desaparece completamente. Es como si se perdiera a la derecha de la ventana y no es accesible. Veo que el `div` contenedor del desplegable de idiomas tiene clases `collapse navbar-collapse` pero no sé si esas clases únicamente funcionan cuando están dentro de un elemento `nav`. El menú sí es un `nav` pero el desplegable de idiomas está fuera (y definido en una plantilla superior).

**Comment by ivarui01** [comment]
Ya lo he arreglado, el problema es que no habia puesto `@register.simple_tag` en el templatetag.
El desplegable de idiomas lo puse fuera del resto de botones para poder ponerlo a la derecha del todo.
Por otro lado, no se si es que me he traido mal los cambios o que pero se han estropeado un poco los estilos:
![image](https://user-images.githubusercontent.com/61693814/116279450-d6bbfd80-a787-11eb-81ca-9abe8794cff6.png)
![image](https://user-images.githubusercontent.com/61693814/116279594-01a65180-a788-11eb-81f8-7956c5f23b66.png)
![image](https://user-images.githubusercontent.com/61693814/116279691-21d61080-a788-11eb-8a5b-0807db0e9434.png)

**Comment by emartinm** [comment]
> Ya lo he arreglado, el problema es que no habia puesto @register.simple_tag en el templatetag.

Perfecto

>  Por otro lado, no se si es que me he traido mal los cambios o que pero se han estropeado un poco los estilos:

Acabo de subir cambios en los que termino de adaptar algunas clases Bootstrap que han cambiado de nombre de BS 4 a BS 5 y quizá esto arregle algunas de los "problemas" visuales que has detectado. También he conseguido meter el desplegable de selección de idioma dentro de la barra de navegación y que esté a la derecha. Ahora ya no desaparece sino que se colapsa con el resto de la barra. He aprovechado para hacer algunos cambios de estilo en el logo y he quitado los bordes de color lavanda que aparecían a izquierda y derecha (eso no es un error, es premeditado).

Si sigues detectando cosas visuales que no te convencen avísame y dime exactamente qué te llama la atención, para saber si es un error inesperado o una "característica" perseguida.

**Comment by ivarui01** [comment]
En cuanto a las traducciones faltan tres palabras en submit.js
`$('#feedback_line').text("Posición: línea " + (line+1) + ", columna " + (col+1));`

**Comment by emartinm** [comment]
Gracias! En el commit a23182b5d50be88660f3a59b387a227222298870 de hace unos minutos debe estar corregido. Básicamente, en lugar de generar la cadena en el JS la he movido a la vista y se pasa dentro del JSON. Concretamente en https://github.com/emartinm/lsql/blob/a23182b5d50be88660f3a59b387a227222298870/lsql/judge/views.py#L406

**Comment by ivarui01** [comment]
¿Qué puede ser esto?
![image](https://user-images.githubusercontent.com/61693814/116614091-c2b7fd80-a939-11eb-8da8-fcfa6fe76e59.png)

**Comment by emartinm** [comment]
Por alguna razón en Windows no está funcionando igual que en Linux y no permite borrar el fichero aunque realmente en ese punto ya ha sido cerrado. Si el test te da problemas, creo que lo más fácil es que comentes esa línea en tu rama **pero no la incluyas en el PR**:

    # os.remove(filename)

Confírmame si así te funciona para avisar a Tamara. En TravisCI no dará problemas porque se ejecuta en Linux y ahora mismo no se está quejando de nada.

**Comment by emartinm** [comment]
Es un test de una funcionalidad *shell* recién añadida, por eso no te había saltado antes.

**Comment by ivarui01** [comment]
Es eso si.

**Comment by emartinm** [comment]
Volviendo sobre el test que fallaba, ya que lo tienes montado, ¿podrías hacer la siguiente prueba a ver si te funciona en Windows? Sería cambiar la parte final de `test_rejudge` por este código, que solo añade el `os.close()` y recupera el `os.remove()`:

    fd, filename = mkstemp('_rejudge')
    os.close(fd)  # To avoid problems when removing the file in Windows
    rejudge(VeredictCode.IE, filename, tests=True)
    with open(filename, 'r') as summary_file:
        summary = summary_file.read()
        self.assertIn('IE --> AC', summary)
        self.assertIn('IE --> WA', summary)
        self.assertIn('IE --> RE', summary)
        self.assertNotIn('IE --> IE', summary)
    os.remove(filename)

Luego lánzalo con `python manage.py test judge.tests.test_shell.ShellTest.test_rejudge` para ver si sigue fallando. Creo que el cierre previo puede eliminar el problema que aparecía al tratar de eliminarlo.

**Comment by ivarui01** [comment]
Así si funciona.

**Comment by emartinm** [comment]
Perfecto, ¡gracias por confirmar! Si puedes meter ese cambio en tu siguiente commit del PR perfecto, y si no te preocupes, ya lo subo yo cuando tu PR esté aceptado.

**Comment by ivarui01** [comment]
Lo subo yo, no hay problema.

**Comment by emartinm** [comment]
¡Muchas gracias!

**Comment by ivarui01** [comment]
![image](https://user-images.githubusercontent.com/61693814/116782198-0a4c9f80-aa88-11eb-9be6-bc7e69f58dee.png)

**Comment by emartinm** [comment]
Es verdad... Pon uno más largo como "file_desc".

**Comment by emartinm** [comment]
Creo que ya solo quedaría lo del idioma de los logros, ¿verdad?

**Comment by ivarui01** [comment]
Y la página de ayuda.

**Comment by emartinm** [comment]
Perfecto, gracias por estar al tanto :smiley:

**Comment by ivarui01** [comment]
Para la página de ayuda, ¿compruebo que existe en el idioma en el que se va a mostrar o doy por hecho que la página existe aunque este vacía?

**Comment by emartinm** [comment]
Desde el punto de vista de la robustez creo que es mejor mostrar la página es español si se solicita un idioma para el que no existe ayuda, en lugar de generar un error 500 (que es lo que pasaría si se asume que esa página va a existir y luego no). Creo que una manera sencilla de hacerlo sería tratar de renderizar la página `help.<language>.html` y capturar la excepción de `plantilla no existente` para renderizar `help.es.html` en su lugar.

Mejor no usar funciones que miran en el sistema de ficheros porque luego las rutas podrían cambiar en el sistema desplegado en el servidor.

**Comment by ivarui01** [comment]
No entiendo por que este código:
![image](https://user-images.githubusercontent.com/61693814/116791627-de4b1180-aabb-11eb-840a-c3cabe4aeded.png)
Me genera esto:
![image](https://user-images.githubusercontent.com/61693814/116791636-ef941e00-aabb-11eb-955a-9700e9f85394.png)
Teniendo esto:
![image](https://user-images.githubusercontent.com/61693814/116791640-fcb10d00-aabb-11eb-9573-6d751f5117b0.png)
Si hago esto `obj.achievement_definition.es` o esto `obj.achievement_definition.en` me devuelve el valor correcto, pero tengo que cambiar ese `es` o `en` por `LANGUAGE_CODE` y no se como hacerlo.

**Comment by ivarui01** [comment]
Me faltaba poner `.items` después de `.name`

**Comment by ivarui01** [comment]
Esta función:
![image](https://user-images.githubusercontent.com/61693814/116792380-86fb7000-aac0-11eb-8294-0d6f4510405d.png)
¿Se puede usar desde las plantillas?

**Comment by ivarui01** [comment]
> Esta función:
> ![image](https://user-images.githubusercontent.com/61693814/116792380-86fb7000-aac0-11eb-8294-0d6f4510405d.png)
> ¿Se puede usar desde las plantillas?

Y esa función, ¿La debería cambiar para que devolviese el nombre en el idioma actual como se ve en la imagen?
Porque entonces tengo que cambiar esto en un test:
![image](https://user-images.githubusercontent.com/61693814/116792894-c8414f00-aac3-11eb-8240-c5bc0d7b4e3f.png)
Que podría fallar si se cambia el idioma principal.

**Comment by ivarui01** [comment]
> Esta función:
> ![image](https://user-images.githubusercontent.com/61693814/116792380-86fb7000-aac0-11eb-8294-0d6f4510405d.png)
> ¿Se puede usar desde las plantillas?

Y a esa función le podría añadir que si no existe el idioma, que muestre el idioma principal.

**Comment by emartinm** [comment]
La función `__str__` es también la que usa la interfaz de administrador cuando tiene que mostrar un objeto de ese tipo. Tocar esa función tiene ese efecto lateral, pero si `name` ahora es un diccionario entonces seguro que había que modificarla. Lo único es que tendría que funcionar sin fallar en entornos donde no haya una traducción disponible (lo digo por el `translation` que no sé de dónde viene)

**Comment by ivarui01** [comment]
![image](https://user-images.githubusercontent.com/61693814/116812078-09ca0c80-ab4d-11eb-8a6a-77186f505b7e.png)
¿Hay alguna manera de hacer esto sin que se piense que le estoy asignando el valor `""` a `settings.LANGUAGE_CODE`? Es que no encuentro nada y tampoco se como expresarlo para buscarlo bien.

**Comment by emartinm** [comment]
Qué es lo que quieres expresar, que el valor por defecto es un diccionario `{'es: ''}`? No te sirve la opción de abajo que usas en `description`?

De todas formas yo no le daría un valor por defecto a "mensaje vacío", dado que son dos cosas bastante imprescindibles para un logro.

**Comment by ivarui01** [comment]
Lo de `description` si me vale, el problema es que sale esto cada vez que se inicia el servidor:
![image](https://user-images.githubusercontent.com/61693814/116868304-d94aa700-ac0e-11eb-9813-9b2457b5b78c.png)
Y no se puede dejar eso así.

**Comment by ivarui01** [comment]
Y ahora esto queda un poco feo, ¿No habría manera de cambiarlo?
![image](https://user-images.githubusercontent.com/61693814/116868623-5f66ed80-ac0f-11eb-8a41-44896c8cf9e8.png)

**Comment by emartinm** [comment]
No, eso es un aviso serio porque compartir estructuras mutables como los diccionarios en valores por defecto puede producir problemas muy locos y difíciles de depurar. Dado que te sugiere un *callable* para evitar compartición, prueba con una función anónima:

    lambda: {clave: valor}

**Comment by emartinm** [comment]
> Y ahora esto queda un poco feo, ¿No habría manera de cambiarlo?

Que yo sepa, no. Si el campo es un JSON y aparece en el interfaz del administrador, esa sería la manera más completa de mostrarlo. Quizá haya una manera de transformar un campo para mostrar ese resultado en la interfaz de administrador en lugar del valor en bruto, pero yo no la conozco (tampoco he personalizado mucho esa interfaz, así que desconozco casi toda su funcionalidad).

Lo que sí tendrá impacto es la función `__str__`, que puedes configurar para que devuelva el nombre en el idioma actual del usuario. Eso hará que se muestre eso en aquellos objetos que tengan una clave externa a una definición de logro (como los logros obtenidos) en lugar de el diccionario.

**Comment by ivarui01** [comment]
Si, aquí si que aparece:
![image](https://user-images.githubusercontent.com/61693814/116869263-b02b1600-ac10-11eb-9793-81ea41d4b74b.png)

**Comment by emartinm** [comment]
Pues es un poco feo, como bien dices, pero creo que se puede vivir con ello. Así queda bien claro y patente que esos dos valores son diccionarios.

**Comment by emartinm** [comment]
Este *issue* ya se puede dar por cerrado, ¿verdad @ivarui01 ?

**Comment by ivarui01** [comment]
Si.

**Comment by emartinm** [comment]
Completado con los PR #68, #74, #76 y #77
