### ISSUE TITLE
Tarea de informar al usuario de los logros conseguidos (dificultad media)

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#65]
Cuando un usuario haga un envío correcto y ese envío le desbloquee uno o varios logros, entonces vea un mensaje informativo **en ese momento** indicando exactamente qué logros acaba de obtener.

Asignada a @Tamiflu9

**Comment by Tamiflu9** [comment]
He hecho un video de como tengo esta tarea:
https://drive.google.com/file/d/1iUH2TYn5YraWBLOGAu8r4mnE3c9Er3fL/view?usp=sharing

Si obtienes un logro te dice que logro has conseguido y si vuelves a enviar el código correcto ya no te cuenta como logro. Si no tienes logros te muestra un mensaje de que no has obtenido logros.

**Comment by emartinm** [comment]
La idea general me parece adecuada, aunque no habría que mostrar nada cuando un envío no te hace conseguir un logro porque eso es lo más normal y puede confundir. En el caso de un envío que consigue logros, incluiría el mensaje de una manera más textual y ligada al mensaje original. Es decir, algo como:

¡Enhorabuena¡ Tu código SQL ha generado los resultados esperados. Además, con este envío acabas de conseguir los logros **Experto en SELECT** y **Rey de los HAVING**. Accede a la página [Mis Logros](blablabla) para más información.

*(Habría que adaptar los plurales convenientemente)*

Creo que ahora mismo los logros existentes en el sistema solo se consiguen con envíos aceptados. Revisa si es así, y en caso afirmativo centrate únicamente en este tipo de envíos para extender la ventana modal.

De todas formas, de la tarea sobre pistas tenemos un PR en curso y faltaría otro más, el de obtener las pistas del ZIP, que no va a ser trivial. Es importante que antes de hacer cualquier PR en esta tarea de avisar sobre los logros estén esos dos PR aceptados.

**Comment by emartinm** [comment]
> Creo que ahora mismo los logros existentes en el sistema solo se consiguen con envíos aceptados. Revisa si es así, y en caso afirmativo centrate únicamente en este tipo de envíos para extender la ventana modal.

Después de leer la memoria he recordado que hay logros que se obtienen con envíos que no son AC.

**Comment by Tamiflu9** [comment]
donde debería meter los tests, en `test_ranking` con los demas tests de los logros o en `test_submit` donde se comprueban los resultados de un envío?

**Comment by emartinm** [comment]
Yo creo que encaja mejor en `test_submit` porque habrá que comprobar que el JSON tiene lo que tiene que tener.
