### ISSUE TITLE
Tarea nuevos tipos de Logros (dificultad baja)

### ISSUE THREAD

**Issue by Dashito14** [emartinm/lsql#67]
- Número de problemas resueltos de un tipo de logro.
- Número de envíos realizados.

**Comment by Dashito14** [comment]
El segundo logro, ¿queréis que sea número de envíos totales o de un problema en concreto? ¿O ese no queréis que se añada?

**Comment by jcorreas** [comment]
No sé si estoy entendiendo bien este logro.

Habría que matizar un poco (hacer muchos envío puede no ser un logro, si no resuelven un problema). Podría ser número de envíos realizados a problemas distintos, o que la razón ejercicios resueltos/envíos realizados sea mayor a 0,5 (es decir, 2 envíos por ejercicio resuelto de media).

**Comment by emartinm** [comment]
Es verdad que en algunos juegos aparecen estos anti-logros como "morirse 100 veces" y cosas así, aunque para un objetivo de aprendizaje no soy capaz de prever su impacto. 

Según hemos diseñado los logros deben ser algo que se obtiene en un momento y luego se mantienen para siempre, así que el logro de tener un promedio resueltos/envíos no encajaría (es algo que fluctúa con el tiempo y que puedes perder si empiezas a fallar mucho). Quizá me cuadra más el logro de "haber realizado envíos a X problemas distintos", que independientemente del resultado de los envíos al menos muestra que ha explorado las colecciones e idealmente leído los enunciados.

**Comment by Dashito14** [comment]
**"haber realizado envíos a X problemas distintos"**

Esto es realizar X envíos a Y problemas, ¿no? Siendo X e Y los números ajustables por el profesor.

**Comment by emartinm** [comment]
Tu opción es más general que la mía, ya que "haber realizado envíos a X problemas distintos" se podría definir como "realizar N envíos a X problemas distintos" con N <= X puesto que se cumplirá en cuanto envíes al problema número X. No sé si querrás comprobar que X >= Y en este tipo de logro, ya que es imposible hacer menos de Y envíos a Y problemas. Pero no pasa nada si no se comprueba porque aún así sería un logro que se consigue en cuanto:
1. Se realizan al menos X envíos
2. Existen envíos para al menos Y problema
