### ISSUE TITLE
Memoria TFG

### ISSUE THREAD

**Issue by Dashito14** [emartinm/lsql#71]
Issue para aclarar dudas, correcciones y mejoras de la memoria.

**Comment by emartinm** [comment]
Menciones para todos, para asegurar que os lleguen los mensajes: @Dashito14 @iburgoa13 @Tamiflu9 @ivarui01 @jcorreas

**Comment by iburgoa13** [comment]
Buenas, he tenido mañana libre y he estado viendo algo como se podría hacer mejorar en la memoria.
1- He conseguido poner los enumerados en el índice, es algo extraño , doc no te pilla 1. TITULO el 1 como numérico, hay que incorporarlo como al título para que lo pille.
2- He quitado lo de las herramientas y puesto aparte, como comentó Enrique eso al final habría que hacerlo dos veces si estuviera en introducción y me da que ahí habrá mucho jaleo y bastante ya en castellano.
3- He añadido más títulos, revisad y añadir y modificar lo que creáis chicos.
4- He cambiado el orden de conclusiones y aportaciones a la inversa como se habló.
En parte poco más, va cogiendo forma el esqueleto,
ya queda menos chicos!! Último empujoncito.

**Comment by Dashito14** [comment]
Respecto a herramientas, ¿hay que poner Django, Oracle y todo esto o solo los editores y Github?

**Comment by emartinm** [comment]
Sobre Django tendréis que hablar porque es el *framework* básico del juez. Oracle habrá que mencionarlo por ser el SGBD que usa el juez, pero no creo que haya que extenderse mucho. Podéis generalizar el título de "Herramientas" a "Preliminares" para contar los aspectos tecnológicos que son necesarios para entender la memoria (sean herramientas, frameworks u otra cosa). Y ese mismo capítulo acomodaría bastante bien a las "plataformas antecesoras" que entiendo que son otros jueces aplicados en el aprendizaje. 

Dejar los "inicios del juez" y la "historia del open source" como capítulos separados me parece bien por ahora, y si salen cortos se podrán fusionar en un capítulo "Estado inicial del juez y metodología de desarrollo"

**Comment by jcorreas** [comment]
Un comentario complementario al de Enrique: sobre Oracle no hace falta hacer una introducción a lo que es y las funcionalidades que ofrece, pues podemos suponer estos conocimientos en el lector (aparte de una frase inicial), pero creo que sí es relevante describir cómo se hace la comunicación con Oracle, como se resuelven las situaciones que se pueden producir (excepciones, errores, etc.), cómo se crea un entorno dentro de Oracle para realizar consultas sin interferencias con otros usuarios (hay que describir cómo se crea el usuario y el schema del usuario, si se destruye al final de cada consulta o al final de la sesión del usuario, si se genera un usuario con nombre único cada vez, así como los casos específicos de ejecución de procedimientos almacenados y de disparadores). También es importante describir en alguna parte de la memoria cómo se realiza el proceso de comparación de resultados y detección de errores de alumnos. Aunque esta parte ya esté presente en la versión de de la que partís para vuestro TFG, creo que es importante describirlo para poder hacer explícita la dimensión completa de la herramienta. Desde mi punto de vista, hacer un juez de SQL como este es bastante más complejo que hacer un juez de programación del tipo de DomJudge (sin quitarle mérito, que está muy bien hecho, pero la verificación de corrección se limita a comparación de textos).

**Comment by Dashito14** [comment]
Hola @jcorreas. Hemos avanzado en la memoria en los puntos: Resumen, Introducción, Herramientas e Implementaciones. Por si puedes ir leyéndolo para el día de la reunión. Avanzaremos estos días algo más pero bueno, con lo que hay ahora yo creo que tenemos varios puntos a discutir en la reunión :D

**Comment by jcorreas** [comment]
Bien, lo miro para la reunión de mañana.

**Comment by Dashito14** [comment]
Como una de mis tareas es crear dos logros nuevos creo que queda un poco coja una sección de las implementaciones solo para esto. Había pensado en incluirla con la explicación de los logros inicial, y agregar una especie de 

> _Tras finalizar otras implementaciones se crean dos logros nuevos para seguir motivando a los alumnos_

obviamente con otra frase pero más o menos con ese significado.

**Comment by emartinm** [comment]
Me parece mejor aglutinarlo en un único apartado de la memoria, como dices, aunque el añadido final estuviera separado en el tiempo de la primera tarea y tuviera issue y PR propio.

**Comment by Dashito14** [comment]
Si queréis podéis revisar el punto 7.11, el del sistema de logros. Falta una mejor redacción pero me gustaría que pudierais corregir el contenido ya que está un poco largo al haber metido dos tareas en una.

**Comment by jcorreas** [comment]
Creo que está bastante bien, en particular me parece bien separar los logros en 7.13.1 en dos grupos que se desarrollaron en momentos distintos. Respecto a 7.13.2, creo que se puede generalizar el texto del principio a todos los logros: donde se dice "...de la cual heredarían los 3 modelos de los logros..." se puede decir que heredan todos los modelos de los logros (es así, ¿no?). La expresión "desbloquear" habría que explicarla un poco, que ni a mí me queda clara (¿se ha bloqueado por algún motivo, o es que todavía no se ha conseguido el logro? En la captura de pantalla posterior, "logros pendientes" queda mucho más claro).
Los dos últimos párrafos son los que se pueden mejorar más. Desde mi punto de vista no es conveniente escribir en primera persona (excepto en el apartado de contribución individual). Creo que es mejor introducir esta parte de otra forma. Por ejemplo: "La introducción de los dos últimos logros descritos en el apartado anterior planteó dificultades adicionales, en particular el logro "NumSolvedTypeAchievement", que considera la resolución de problemas de un mismo tipo, ya que los tipos de problemas pueden variar al introducir nuevos ejercicios..."  (la redacción no es definitiva, seguramente la corregiré más adelante, pero da una idea de la forma de introducir esta parte).

**Comment by iburgoa13** [comment]
Me cuelo también por aquí.
@jcorreas @emartinm 
Acabados están mis puntos de Implementaciones y Contribuciones.
Implementaciones: 7.1 7.2 7.3 7.4 7.5 7.9
Contribuciones: 8.1 
Lo que sí obviar aún quizás el tema de verbos que tengo que ver alguna cosa más, pero más que nada por ver cómo está todo compuesto, si está correcto, etc.
Me faltaría completar el punto 1 entero (Introducción) a lo largo de la semana lo haré y os lo haré llegar

**Comment by Tamiflu9** [comment]
Podéis mirar los puntos:  7.7  7.12  7.19 (quitando el recuento de asserts y de comentarios que tengo que cambiarlo)

**Comment by jcorreas** [comment]
Hola a todos, no voy a poder revisar nada de la memoria del TFG esta semana. Miraré todo lo que hayáis añadido a la memoria el lunes, por si queréis añadir algo más durante estos días.

**Comment by iburgoa13** [comment]
@jcorreas está "terminado" los puntos 1 y mis 7 (1,2,3,4,5,9) y 8.
Me falta por completar los 7 con los usos ya que no he tenido mi portatil este finde y no he podido acceder a linux para hacer las capturas y demás. Si puedo esta noche adelanto cositas de ahí.
Un saludo.

**Comment by Tamiflu9** [comment]
@jcorreas al punto 4 de **Plataformas antecesoras** le puedes echar un ojo también? para ver más o menos que cosas modificar

**Comment by jcorreas** [comment]
Hola, @Tamiflu9 @iburgoa13 @Dashito14 @ivarui01. Estoy revisando los textos que vais introduciendo en la memoria. En muchos casos estoy haciendo correcciones directamente sobre el texto: aunque no es la mejor forma de ayudaros a mejorar la memoria, es la más rápida. En cualquier caso, no basta con aceptar mis cambios: tenéis que verificar el texto que he escrito yo y, si lo veis necesario, completarlo. Mi objetivo con estas correcciones no es tanto que quede mejor la memoria, sino que veáis otras posibles redacciones que mejoran la legibilidad del texto y que apliquéis estas mismas ideas en el resto de la memoria.

En otros casos os pongo comentarios para que seáis vosotros los que cambiéis la redacción del texto. Y en los casos en los que indico "no se entiende", no quiero decir que yo no lo entiendo, sino que un lector ajeno a este proyecto no lo va a entender o está mal redactado y para mejorarlo habría que volver a escribirlo. Con este comentario lo que quiero es que volváis a escribir el texto, no que me expliquéis lo que queréis decir.

**Comment by iburgoa13** [comment]
Buenas,
Tenemos una duda, había un apartado en el 7.X (ya no) que era el conflicto de Tamara y Dani (Ranking con Logros), hemos pensado ponerlo en el punto 6, ya que es un claro ejemplo de conflictos y podía tener mejor relación. El problema, que perdemos información ya que no podemos mencionar las tareas siguientes (descargar ranking con logros etc) pero en el 7 se queda una tarea muy coja.
¿Dónde encajaría mejor @jcorreas @emartinm?
Muchas gracias.

**Comment by jcorreas** [comment]
Hola, @iburgoa13 @Tamiflu9 @Dashito14 (y @emartinm ). Este es un aspecto interesante de la metodología de desarrollo. Podéis añadir un (sub)apartado en el capítulo 6 (por ejemplo, "Resolución de conflictos de desarrollo" o algo así) en el que ponéis este ejemplo como un caso característico de este tipo de conflictos y describís brevemente las dos tareas (con sendas referencias al capítulo 7) para explicar el conflicto y su resolución. Y después en el capítulo 7 (preferiblemente en la última de las dos tareas, Logros, o en la última cronológicamente --creo recordar que era el ranking, pero no recuerdo) en el que detalláis en la sección de desarrollo la resolución de este conflicto, los cambios que ha supuesto, etc.

Algunos elementos como este deben estudiarse desde múltiples puntos de vista, por lo que deben aparecer en distintos capítulos (no se está repitiendo exactamente lo mismo, sino describiendo dos facetas del proceso de desarrollo).

**Comment by ivarui01** [comment]
@jcorreas he corregido y ampliado el punto **5. Estado inicial de LearnSQL**

**Comment by Dashito14** [comment]
Buenas, necesitamos saber la versión de Linux que hay en la Facultad.

**Comment by emartinm** [comment]
> Buenas, necesitamos saber la versión de Linux que hay en la Facultad.

Lo he contestado en un comentario en la memoria, pero por si acaso es **Ubuntu 20.04**

**Comment by iburgoa13** [comment]
@jcorreas @emartinm @Tamiflu9 @Dashito14 Tenéis en la siguiente ruta (https://drive.google.com/drive/folders/1-XY8ZScqRUndfhg_GryK-2nxliT3zWG1) el TFG hasta la fecha de hoy. El miércoles comentamos, no es la definitiva, aún queda alguna corrección, faltan también la revisión del punto 5 de Iván y revisiones de algunos puntos sueltos más y realizar los puntos en Inglés cuando estén okey los demás. Si queréis hacer alguna anotación, podéis hacerla en el doc directamente.
El miércoles comentamos,
Un saludo.

**Comment by jcorreas** [comment]
Gracias Iker por la última versión. He revisado muy rápidamente el texto en google docs y lo habéis mejorado mucho. Aun así, tengo comentarios y sugerencias que incluir. En cualquier caso lo hablamos el miércoles en la reunión. Todavía no traduzcáis el texto de la introducción y las conclusiones, algunos comentarios son de esos dos capítulos.

**Comment by Dashito14** [comment]
@jcorreas he aceptado muchos de los cambios que has sugerido en el punto 3, algunos los he retocado y he dejado dos comentarios de respuesta a tus cambios sugeridos. Te lo digo por aquí porque seguro que después de aceptar tantos cambios no habrás podido ver estas respuestas.

**Comment by Tamiflu9** [comment]
Tengo dos duda, los lenguajes de programación como : C, C++, Java,.. etc. como deben ir? Y las extensiones de los archivos: .sql, .xls, etc.. ? Es que hemos estado cambiando varias veces y no se al final que opción sería mejor. 
@jcorreas, @emartinm

**Comment by jcorreas** [comment]
Hola, creo que al final hemos dicho que los nombres propios (incluyendo lenguajes) deben ir en mayúsculas y sin cursiva. Las palabras en inglés (feedback) en cursiva. Si alguna frase está íntegramente en inglés, en cursiva y con comillas ("404 Not found").

Si no es correcto, decidlo para tener una referencia común.

**Comment by Dashito14** [comment]
¿Y las extensiones que teníamos en Courier? Las dejamos en Courier o las ponemos en Arial. También hay correcciones de negrita pero eso no creo que quede bien, como nos digáis.

**Comment by jcorreas** [comment]
Bien, en ese caso yo prefiero que los textos literales de código o nombres de fichero aparezcan en Courier. 

Si decidís lo contrario, me parecerá bien, pero lo importante es ser consistentes en todo el documento.

**Comment by emartinm** [comment]
La culpa es mía, que he cambiado algunos a Arial. Pero hacedlo tal y como os dijera Jesús en su momento.

Eso sí, en una frase como "...guardamos un fichero XLSX para poder..." lo único que debe estar en Courier es **XLSX**, **no el espacio anterior ni el posterior** porque entonces ocupa el doble y queda feote

**Comment by Dashito14** [comment]
En cuanto al punto 8 estoy viendo las correcciones de Enrique. Las opiniones que no son contribuciones ¿no están bien para presentar la tarea? Así también se habla de motivación a los alumnos (por ejemplo) como contribución. Si hay que eliminar los puntos de opiniones se queda en una lista de tareas que hemos hecho. O no sé como hay que enfocar ese punto.

**Comment by emartinm** [comment]
Ya he terminado mi pasada y aunque he puesto algunos comentarios, realmente son todo cosas menores. Ahora revisaré los miles de mensajes que me han llegado por si hace falta que conteste. En resumen, las cosas que he detectado son:
 
- Frases que quizá son confusas y propongo alternativas, o verbos que son informales o se repiten.
 - Figuras poco legibles. A veces hay capturas con letra diminuta que tienen mucho espacio en blanco. Haced la ventana más pequeña y quedará más grande.
 - Cosas tontas como dobles espacios, espacios Courier que son más grandes, páginas en blanco al final de unos capítulos sí y otros no, títulos huérfanos al final de una página o líneas viudas al inicio de página hacen que un lector se lleve la impresión de escritura precipitada. Una vez tengáis la versión definitiva, dedicad 10 minutos a detectarlo y cambiarlo.
 - En la sección de contribuciones hay algunas partes que no informan de qué habéis hecho sino que son puramente opinativas. Seguramente el tribunal no tenga problema con ello, pero a mi me chocan un poco. Sobre todo si hay uno o dos párrafos largos de valoración y opinión.
 - El nombre de los tipos de problemas: "problema tipo SELECT", "problema de consultas"... aseguraos de que cuando los presentáis en el documento el lector entiende que tienen varios nombres, o unificarlos en el documento.

**Comment by emartinm** [comment]
> En cuanto al punto 8 estoy viendo las correcciones de Enrique. Las opiniones que no son contribuciones ¿no están bien para presentar la tarea? Así también se habla de motivación a los alumnos (por ejemplo) como contribución. Si hay que eliminar los puntos de opiniones se queda en una lista de tareas que hemos hecho. O no sé como hay que enfocar ese punto.

Nada, dejadlo como está, era solo un comentario.

**Comment by emartinm** [comment]
Hay otra cosa que no me termina de convencer, que es la frase final del número de asertos que ejecutan vuestros tests de unidad. Lo decís de varias maneras, con varios verbos diferentes, y a veces parece que sois vosotros los que durante la elaboración de los tests realizasteis X comprobaciones. Quizá podáis mencionar *aserto* y decir algo como:

    En total, los tests de unidad generados para esta tarea comprueban X asertos. 

o

    Los tests de unidad generados para esta tarea comprueban un total de X asertos.

**Comment by Dashito14** [comment]
Me parece bien cambiar esas frases, pero quizás mencionar los asertos es algo más confuso ya que no sé si aserto es algo que todo el mundo sabe a lo que se refiere, por eso hablamos de poner "comprobaciones"

**Comment by emartinm** [comment]
Yo también pensaba así, pero creo que en un contexto informático y concretamente en la sección de tests de unidad es un conocimiento que se podría suponer en el lector. En cualquier caso, que quede claro que son los tests de unidad los que realizan o están compuestos por esos asertos/comprobaciones/cosas.

**Comment by Dashito14** [comment]
Para ir terminando apartados, hemos contestado a algunos de los comentarios. En el punto 3 he reescrito algunas cosas que he marcado en comentarios. También he añadido dos comentarios en 7.13.1 y 7.13.2 para cuando podáis verlos. Aviso por aquí, igual que las otras veces, porque es un caos los mensajes que nos llegan a todos y es normal que se pierdan.

**Comment by iburgoa13** [comment]
Han subido el drive, una pregunta, venía una autorización para descargar y hacer todo lo que hicimos. He subido la que se hizo el otro día, ¿no habría problema, no? Estéticamente es algo diferente pero pide lo mismo. @jcorreas @emartinm

**Comment by emartinm** [comment]
Yo también la he visto y me parecía equivalente a la que firmamos salvo el formato, que es un poco más bonito. Si habéis comprobado con detalle que el texto es fundamentalmente el mismo, podemos dejar la que tenemos.

**Comment by iburgoa13** [comment]
Así se quedará pues, dudo que pongan pegas. Muchas gracias.

**Comment by Dashito14** [comment]
En cuanto a la presentación, tenemos 5 minutos cada uno. ¿Qué estructura es mejor? ¿Qué cada uno hable sus 5 minutos de seguido o vayamos alternando? Si lo hacemos seguido yo creo que rompería un poco la estructura de la presentación porque cada uno deberá hablar de alguno de los puntos (presentación, conclusión...) y además de los apartados hechos por él mismo. No sabemos bien como hacerlo, por si nos podéis guiar.

**Comment by jcorreas** [comment]
> Para ir terminando apartados, hemos contestado a algunos de los comentarios. En el punto 3 he reescrito algunas cosas que he marcado en comentarios. También he añadido dos comentarios en 7.13.1 y 7.13.2 para cuando podáis verlos. Aviso por aquí, igual que las otras veces, porque es un caos los mensajes que nos llegan a todos y es normal que se pierdan.

@Dashito14 no he visto comentarios en el capítulo 3. Creo que he contestado los de 7.13, pero avisadme por aquí, que tengo bastante cacao con la cantidad de mensajes que se reciben y comentarios que aparecen en google docs.

También he terminado de revisar la traducción. Creo que está todo muy bien. Pero yo soy bastante neurótico con la versión final de documentos de esta dimensión y creo que os vendría muy bien hacer una lectura completa (después de descansar, para que sea de nuevas) para detectar erratas, posibles omisiones, etc.

**Comment by Dashito14** [comment]
Si, vamos a hacer una reunión mañana seguramente para cerrar todo, leyendo todo y dejándolo listo.

**Comment by emartinm** [comment]
> En cuanto a la presentación, tenemos 5 minutos cada uno. ¿Qué estructura es mejor? ¿Qué cada uno hable sus 5 minutos de seguido o vayamos alternando? Si lo hacemos seguido yo creo que rompería un poco la estructura de la presentación porque cada uno deberá hablar de alguno de los puntos (presentación, conclusión...) y además de los apartados hechos por él mismo. No sabemos bien como hacerlo, por si nos podéis guiar.

Yo creo que para la presentación mejor minimizar el cambio de presentadores. Podéis dividir la presentación en 3 partes y que cada uno cuente una (da igual si habláis de tareas que hay hecho otro, de hecho no podréis hablar de todas). Al final, podéis hacer una ronda rápida estilo Eurovisión para que cada uno diga sus contribuciones en inglés.

Para la presentación lo que tiene que quedar claro es:

 - Qué habéis hecho y por qué es relevante
 - Características concretas del desarrollo del proyecto para entender el contexto
 - Principales mejoras añadidas (organizarlo en familias, como los objetivos, y no seáis exhaustivos porque no podéis). Aquí podéis incluir ejemplos donde se vea el juez con esas mejoras seleccionadas.
 - Conclusiones y trabajo futuro

Y creo que con eso y poco más ya habéis llenado los 20 minutos

**Comment by Tamiflu9** [comment]
Hemos subido la versión final de la memoria al drive : [https://drive.google.com/drive/u/0/folders/15LFzXMEF91TeIzkl_2dy9nBe0nr5sEiq ](url)

Por otro lado, la tarea de informar de los logros se va a quedar así. He dejado indicado en la memoria que quedaría pendiente modificar lo del mensaje agrupado en una frase.

**Comment by emartinm** [comment]
> Por otro lado, la tarea de informar de los logros se va a quedar así. 

Vaya, la verdad que no tenía ni idea, pensaba que lo ibas a terminar del todo.

> He dejado indicado en la memoria que quedaría pendiente modificar lo del mensaje agrupado en una frase.

Entonces vamos a hacer una cosa, porque no me parece adecuado aceptar un PR cuando todavía le quedan comentarios abiertos (de la misma manera que no he aceptado ningún otro PR con comentarios abiertos). En lugar de incluir el enlace al PR incluye un enlace a la rama de tu proyecto y menciona que no se ha terminado por integrar por falta de tiempo para procesar todas las revisiones recibidas. Yo por mi parte lo que haré será cerrar el PR #88 sin integrar.

**Comment by Tamiflu9** [comment]
Es que pensé solo tenía hasta el viernes o el sábado, pero he visto el correo que me mandaste el otro día. Estoy intentando arreglarlo y a ver si hoy consigo terminarlo. Si no, mañana como hay que subir la memoria hago lo que has dicho

**Comment by emartinm** [comment]
Yo te propongo una cosa: como la fecha de entrega de la memoria es el 15, trata de tener el código para el 15 por la mañana (opción A). Que nos da para tenerlo todo en ese momento, perfecto. Que no, déjalo en tu rama y enlaza eso en la memoria en lugar del PR (opción B). Eso siempre y cuando tengas tiempo disponible hasta el martes por la mañana. Si justo estos días necesitas todo el tiempo para estudiar, mi recomendación es ir directamente a la opción B.

**Comment by Tamiflu9** [comment]
La opción A. 
La memoria ya estaría actualizada, por si mañana la queréis revisar.

**Comment by emartinm** [comment]
Gracias! Si, yo mañana quiero revisar el texto de esta última tarea de mostrar lo logros.

**Comment by emartinm** [comment]
Acabo de revisar los dos últimos puntos del tema 7, ambos de Tamara, con algunas correcciones y sugerencias menores. Por mi parte no tendría nada más que comentar en la memoria (avisadme si se me ha quedado algún comentario abierto).

Ánimo con le vídeo, y si tenéis cualquier duda sobre la presentación avisadnos.

**Comment by jcorreas** [comment]
Hola, os recuerdo que hoy tenéis que entregar la memoria final. Avisadnos si tenéis alguna duda.

**Comment by Tamiflu9** [comment]
Hola, sí hemos entregado ya la memoria. Gracias.
