### ISSUE TITLE
Problemas al comparar tablas con orden

### ISSUE THREAD

**Issue by emartinm** [emartinm/lsql#83]
En el problema https://learn.fdi.ucm.es/sql/problem/17 se detecta la siguiente solución como incorrecta, pero está devolviendo los resultados esperados incluyendo el orden de las filas:

    SELECT LOWER(Sede) AS "Lugar", CIF AS "Identificador"
    FROM Club
    WHERE Num_Socios > 50000
    ORDER BY Num_Socios DESC, CIF ASC

La causa debe ser una interacción extraña entre los nombres de las columnas y la comprobación de filas, porque al quitar las comillas sí que funciona adecuadamente.

    SELECT LOWER(Sede) AS Lugar, CIF AS Identificador
    FROM Club
    WHERE Num_Socios > 50000
    ORDER BY Num_Socios DESC, CIF ASC

**Comment by jcorreas** [comment]
Yo creo que se debe a que las dobles comillas obligan a mantener mayúsculas y minúsculas exactamente como están, mientras que el nombre sin comillas se cambia a mayúsculas automáticamente, que es como se guarda en el diccionario de datos de Oracle.

Por ejemplo, la consulta SELECT Sede FROM Club; funciona correctamente.

Pero SELECT "Sede" FROM Club; es incorrecta, mientras que SELECT "SEDE" FROM Club es correcta.

Creo que LearnSQL no debe hacer nada con esto, forma parte del comportamiento correcto de Oracle. Las comillas dobles no representan un literal de texto, sino un identificador con las mayúsculas y minúsculas fijadas estrictamente.

**Comment by emartinm** [comment]
Para comprobar la corrección del resultado de una consulta, LearnSQL realiza 2 comprobaciones:

1. Que el esquema es correcto: tienen el mismo número de columnas, los nombres "coinciden" y los tipos son iguales.
2. Que las filas son las que tienen que ser, considerando el orden si el problema era de orden.

En este caso había un bug porque el juez mostraba un error de diferencia en las filas, cuando estas era idénticas. De existir un error debería ser en el esquema. Eso lo acabo de arreglar.

Sin embargo, hay un detalle con los nombres de columnas durante la comprobación: **ignora mayúsculas/minúsculas**. Esto lo hice porque realmente no me preocupaba si una columna se llama "Club", "CLUB" o "club", mientras sean esas letras. Otra, más práctica, es porque la colección de problemas que había hecho es imprecisa con respecto al nombre de las columnas. En este ejemplo, el enunciado indica que el esquema esperado es `(Lugar, Identificador)`, pero mi solución oficial es `SELECT LOWER(Sede) AS Lugar, CIF AS Identificador...`. Es decir, si un estudiante era de verdad preciso y enviaba `SELECT LOWER(Sede) AS "Lugar", CIF AS "Identificador"...`, el comprobador original *case-sensitive* le devolvía que la consulta era incorrecta porque la columna `Lugar` se debía llamar `LUGAR`. Y es algo que me pasó durante el curso. Como tardaba menos en flexibilizar el comparador que en cambiar todos los ejercicios, y además me parecía algo justificado, me decanté por esta opción. Pero como ya ha terminado el curso se podría replantear. ¿Tú qué piensas, @jcorreas ? Yo soy partidario de flexibilizar el case-sensitive en nombres de columna, pero si ves que es inadecuado se puede forzar.

**Comment by jcorreas** [comment]
Creo que debe ser flexible e ignorar mayúsculas y minúsculas, aun en el caso en el que se haya creado la tabla utilizando un nombre literal (entre comillas dobles). Esta posibilidad existe en Oracle para casos muy concretos y en cierto sentido polémicos (por ejemplo, para añadir espacios o caracteres especiales a nombres de columna) y no tiene el significado de "cadena de caracteres" de otros lenguajes. Si no se usan comillas dobles, el sistema por defecto convierte a mayúsculas los nombres de columna, que es como están almacenados en el diccionario de datos. En un curso introductorio creo que añadir estos detalles no ayuda para animar al estudiante a realizar ejercicios de BD. La naturaleza de SQL es que se ignoren mayúsculas/minúsculas tanto en las palabras clave como en los nombres de columna, y creo que debe seguir siendo así.

Por otra parte, mi opinión es que nunca se deben utilizar identificadores o nombres de columna que incluyan caracteres especiales, acentos, etc. que requieran comillas dobles. Ya me ha ocurrido unas cuantas veces (por ejemplo en FP) que los alumnos utilizan nombres de variables con acentos y ñ, que su compilador particular permite utilizar, pero cualquier otro compilador falla (utilizar gcc+linux suele ayudar a detectar estos casos). Utilizar esos símbolos y caracteres es una decisión incorrecta y me parece que no ayuda a los alumnos el animarles a utilizar identificadores con caracteres especiales, cuando la realidad de la vida del desarrollador es que no se sabe dónde se va a tener que compilar y utilizar un programa. Utilizarlos es una buena forma de buscarse problemas en el futuro.

**Comment by emartinm** [comment]
Resuelto en commit 97cd63f7b756528b6be00bfc5406ebbc5a906607. Al final he dejado la opción flexible en la que el esquema se compara sin tener en cuenta las mayúsculas.
